/* Generated by Nim Compiler v0.20.99 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef NI32 tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg;
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
NCSTRING name;
TNimType* nextType;
NI instances;
NI sizes;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
NU raiseId;
Exception* up;
};
struct tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g {
  Exception Sup;
tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg code;
};
typedef tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg tyArray__r9a1vSrQqNjC4iSkeSCZBVw[9];
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
NI allocCounter;
NI deallocCounter;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_STDCALL(void, glClearColor)(NF32 red, NF32 green, NF32 blue, NF32 alpha);
N_LIB_PRIVATE N_NIMCALL(void, checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw)(void);
N_LIB_PRIVATE N_NIMCALL(tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg, getGLerrorCode__7adr7YxxCDnx5qZN9b2oelQ)(void);
N_STDCALL(NU32, glGetError)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g*, new__YgQmK9b6iECf2h9bYwxAeb5w)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef__1f3aVIhboUJS2OaJ0h5DXA)(void* p, NI op);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr);
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__Y66tOYFjgwJ0k4aLz4bc0Q)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_STDCALL(void, glClear)(NU32 mask);
NIM_BOOL gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
NIM_BOOL gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI__XEycrCsme5C8CVWAYEcdBQ_;
extern TNimType* nimTypeRoot;
TNimType NTI__wF8RIFtaMM1xhc9cykFAs8g_;
TNimType NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_;
TNimType NTI__1f3aVIhboUJS2OaJ0h5DXA_;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__IcYaEuuWivYAS86vFMTS3Q;
NIM_CONST tyArray__r9a1vSrQqNjC4iSkeSCZBVw AllErrorCodes__uuQ5exRDU8GgDnqBcqZ3Cw = {((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 0),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1280),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1281),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1282),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1283),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1284),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1285),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1286),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 32817)}
;
STRING_LITERAL(TM__5OHv4B5juaNW3eJpx9bSMRg_5, "OpenGL error: ", 14);
STRING_LITERAL(TM__5OHv4B5juaNW3eJpx9bSMRg_7, "OpenGL error: unknown (", 23);
STRING_LITERAL(TM__5OHv4B5juaNW3eJpx9bSMRg_8, ")", 1);

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA9_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg, getGLerrorCode__7adr7YxxCDnx5qZN9b2oelQ)(void) {
	tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg result;
	NU32 T1_;
	nimfr_("getGLerrorCode", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	result = (tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg)0;
	nimln_(77, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	T1_ = (NU32)0;
	T1_ = glGetError();
	result = ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg)chckRange(T1_, ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 0), ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 32817)));
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef__1f3aVIhboUJS2OaJ0h5DXA)(void* p, NI op) {
	tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g* a;
	a = (tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.up, op);
}

static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == NIM_NIL))) goto LA3_;
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}

static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "/p/Nim/lib/system/gc.nim");
	nimln_(183, "/p/Nim/lib/system/gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "/p/Nim/lib/system/gc.nim");
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(129, "/p/Nim/lib/system/gc.nim");
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI) 16)))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "/p/Nim/lib/system/gc.nim");
	nimln_(195, "/p/Nim/lib/system/gc.nim");
	addZCT__Y66tOYFjgwJ0k4aLz4bc0Q((&gch__IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "/p/Nim/lib/system/gc.nim");
	nimln_(200, "/p/Nim/lib/system/gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) - (NU64)(((NI) 8)));
	nimln_(201, "/p/Nim/lib/system/gc.nim");
	{
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(202, "/p/Nim/lib/system/gc.nim");
		rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "/p/Nim/lib/system/gc.nim");
	nimln_(238, "/p/Nim/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(src);
		incRef__AT1eRuflKWyTTBdLjEDZbg_3system(T5_);
	}
	LA3_: ;
	nimln_(239, "/p/Nim/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem((*dest));
		decRef__AT1eRuflKWyTTBdLjEDZbgsystem(T10_);
	}
	LA8_: ;
	nimln_(240, "/p/Nim/lib/system/gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw)(void) {
	tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg error;
	tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g* exc;
	NimStringDesc* T21_;
	nimfr_("checkGLerror", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
{	nimln_(90, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	error = getGLerrorCode__7adr7YxxCDnx5qZN9b2oelQ();
	nimln_(91, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		if (!(error == ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 0))) goto LA3_;
		nimln_(92, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(95, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	exc = new__YgQmK9b6iECf2h9bYwxAeb5w();
	{
		tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg e;
		NI i;
		e = (tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg)0;
		nimln_(17, "/p/Nim/lib/system/iterators.nim");
		i = ((NI) 0);
		nimln_(18, "/p/Nim/lib/system/iterators.nim");
		{
			if (!(((NI) (i)) <= ((NI) 8))) goto LA8_;
			{
				nimln_(19, "/p/Nim/lib/system/iterators.nim");
				while (1) {
					NI TM__5OHv4B5juaNW3eJpx9bSMRg_6;
					nimln_(96, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
					e = AllErrorCodes__uuQ5exRDU8GgDnqBcqZ3Cw[(i)- 0];
					nimln_(97, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
					{
						NimStringDesc* T16_;
						if (!(e == error)) goto LA14_;
						nimln_(98, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
						T16_ = (NimStringDesc*)0;
						T16_ = rawNewString((reprEnum((NI)e, (&NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_)) ? reprEnum((NI)e, (&NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_))->Sup.len : 0) + 14);
appendString(T16_, ((NimStringDesc*) &TM__5OHv4B5juaNW3eJpx9bSMRg_5));
appendString(T16_, reprEnum((NI)e, (&NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_)));
						asgnRef((void**) (&(*exc).Sup.message), T16_);
						nimln_(99, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
						raiseExceptionEx((Exception*)exc, "GLerror", "checkGLerror", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim", 99);
					}
					LA14_: ;
					nimln_(21, "/p/Nim/lib/system/iterators.nim");
					{
						if (!(((NI) 8) <= ((NI) (i)))) goto LA19_;
						goto LA10;
					}
					LA19_: ;
					nimln_(22, "/p/Nim/lib/system/iterators.nim");
					TM__5OHv4B5juaNW3eJpx9bSMRg_6 = addInt(i, ((NI) 1));
					if (TM__5OHv4B5juaNW3eJpx9bSMRg_6 < 0 || TM__5OHv4B5juaNW3eJpx9bSMRg_6 > 8) raiseOverflow();
					i = (NI)(TM__5OHv4B5juaNW3eJpx9bSMRg_6);
				}
			} LA10: ;
		}
		LA8_: ;
	}
	nimln_(101, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	(*exc).code = error;
	nimln_(102, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	T21_ = (NimStringDesc*)0;
	T21_ = rawNewString((reprEnum((NI)error, (&NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_)) ? reprEnum((NI)error, (&NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_))->Sup.len : 0) + 24);
appendString(T21_, ((NimStringDesc*) &TM__5OHv4B5juaNW3eJpx9bSMRg_7));
appendString(T21_, reprEnum((NI)error, (&NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_)));
appendString(T21_, ((NimStringDesc*) &TM__5OHv4B5juaNW3eJpx9bSMRg_8));
	asgnRef((void**) (&(*exc).Sup.message), T21_);
	nimln_(103, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	raiseExceptionEx((Exception*)exc, "GLerror", "checkGLerror", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim", 103);
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glClearColor__mRmvKpMRWVe0olxA2D6ibg)(NF32 red, NF32 green, NF32 blue, NF32 alpha) {
	nimfr_("glClearColor", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glClearColor(red, green, blue, alpha);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glClear__bP2CTzt9boHsiXofCPEwKlw)(NU32 mask) {
	nimfr_("glClear", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glClear(mask);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, opengl_openglInit000)(void) {
{
	nimfr_("opengl", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl.nim");
	nimln_(117, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw = NIM_TRUE;
	nimln_(118, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg = NIM_FALSE;
	popFrame();
}
}

N_LIB_PRIVATE N_NIMCALL(void, opengl_openglDatInit000)(void) {
static TNimNode* TM__5OHv4B5juaNW3eJpx9bSMRg_2_9[9];
NI TM__5OHv4B5juaNW3eJpx9bSMRg_4;
static char* NIM_CONST TM__5OHv4B5juaNW3eJpx9bSMRg_3[9] = {
"no error", 
"invalid enum", 
"invalid value", 
"invalid operation", 
"stack overflow", 
"stack underflow", 
"out of memory", 
"invalid framebuffer operation", 
"table too large"};
static TNimNode TM__5OHv4B5juaNW3eJpx9bSMRg_0[11];
NTI__wF8RIFtaMM1xhc9cykFAs8g_.size = sizeof(tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g);
NTI__wF8RIFtaMM1xhc9cykFAs8g_.kind = 17;
NTI__wF8RIFtaMM1xhc9cykFAs8g_.base = (&NTI__XEycrCsme5C8CVWAYEcdBQ_);
NTI__wF8RIFtaMM1xhc9cykFAs8g_.name = "GLerror";
NTI__wF8RIFtaMM1xhc9cykFAs8g_.nextType = nimTypeRoot; nimTypeRoot=&NTI__wF8RIFtaMM1xhc9cykFAs8g_;
NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_.size = sizeof(tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg);
NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_.kind = 14;
NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_.base = 0;
NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_.flags = 3;
NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_.name = "GLerrorCode";
NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_.nextType = nimTypeRoot; nimTypeRoot=&NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_;
for (TM__5OHv4B5juaNW3eJpx9bSMRg_4 = 0; TM__5OHv4B5juaNW3eJpx9bSMRg_4 < 9; TM__5OHv4B5juaNW3eJpx9bSMRg_4++) {
TM__5OHv4B5juaNW3eJpx9bSMRg_0[TM__5OHv4B5juaNW3eJpx9bSMRg_4+1].kind = 1;
TM__5OHv4B5juaNW3eJpx9bSMRg_0[TM__5OHv4B5juaNW3eJpx9bSMRg_4+1].offset = TM__5OHv4B5juaNW3eJpx9bSMRg_4;
TM__5OHv4B5juaNW3eJpx9bSMRg_0[TM__5OHv4B5juaNW3eJpx9bSMRg_4+1].name = TM__5OHv4B5juaNW3eJpx9bSMRg_3[TM__5OHv4B5juaNW3eJpx9bSMRg_4];
TM__5OHv4B5juaNW3eJpx9bSMRg_2_9[TM__5OHv4B5juaNW3eJpx9bSMRg_4] = &TM__5OHv4B5juaNW3eJpx9bSMRg_0[TM__5OHv4B5juaNW3eJpx9bSMRg_4+1];
}
TM__5OHv4B5juaNW3eJpx9bSMRg_0[1].offset = 0;
TM__5OHv4B5juaNW3eJpx9bSMRg_0[2].offset = 1280;
TM__5OHv4B5juaNW3eJpx9bSMRg_0[3].offset = 1281;
TM__5OHv4B5juaNW3eJpx9bSMRg_0[4].offset = 1282;
TM__5OHv4B5juaNW3eJpx9bSMRg_0[5].offset = 1283;
TM__5OHv4B5juaNW3eJpx9bSMRg_0[6].offset = 1284;
TM__5OHv4B5juaNW3eJpx9bSMRg_0[7].offset = 1285;
TM__5OHv4B5juaNW3eJpx9bSMRg_0[8].offset = 1286;
TM__5OHv4B5juaNW3eJpx9bSMRg_0[9].offset = 32817;
TM__5OHv4B5juaNW3eJpx9bSMRg_0[10].len = 9; TM__5OHv4B5juaNW3eJpx9bSMRg_0[10].kind = 2; TM__5OHv4B5juaNW3eJpx9bSMRg_0[10].sons = &TM__5OHv4B5juaNW3eJpx9bSMRg_2_9[0];
NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_.node = &TM__5OHv4B5juaNW3eJpx9bSMRg_0[10];
NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_.flags = 1<<2;
TM__5OHv4B5juaNW3eJpx9bSMRg_0[0].kind = 1;
TM__5OHv4B5juaNW3eJpx9bSMRg_0[0].offset = offsetof(tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g, code);
TM__5OHv4B5juaNW3eJpx9bSMRg_0[0].typ = (&NTI__ovQg9aLuoEQKuJYv9aVXA3Jg_);
TM__5OHv4B5juaNW3eJpx9bSMRg_0[0].name = "code";
NTI__wF8RIFtaMM1xhc9cykFAs8g_.node = &TM__5OHv4B5juaNW3eJpx9bSMRg_0[0];
NTI__1f3aVIhboUJS2OaJ0h5DXA_.size = sizeof(tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g*);
NTI__1f3aVIhboUJS2OaJ0h5DXA_.kind = 22;
NTI__1f3aVIhboUJS2OaJ0h5DXA_.base = (&NTI__wF8RIFtaMM1xhc9cykFAs8g_);
NTI__1f3aVIhboUJS2OaJ0h5DXA_.name = "ref GLerror";
NTI__1f3aVIhboUJS2OaJ0h5DXA_.nextType = nimTypeRoot; nimTypeRoot=&NTI__1f3aVIhboUJS2OaJ0h5DXA_;
NTI__1f3aVIhboUJS2OaJ0h5DXA_.marker = Marker_tyRef__1f3aVIhboUJS2OaJ0h5DXA;
}

