/* Generated by Nim Compiler v0.20.99 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct tyObject_ExampleApp__wvlZowQbd9bpaVzqNaWWC0Q tyObject_ExampleApp__wvlZowQbd9bpaVzqNaWWC0Q;
typedef struct NimStrPayload NimStrPayload;
typedef struct AllocatorObj AllocatorObj;
typedef struct NimStringV2 NimStringV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct TSafePoint TSafePoint;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ tySequence__4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct tyObject_ExampleApp__wvlZowQbd9bpaVzqNaWWC0Q {
NU32 program;
NU32 vertexBuffer;
double lastTouchX;
double lastTouchY;
double offsetX;
double offsetY;
};
typedef NU8 tyEnum_GLFMRenderingAPI__89azhV1FN9ch7ehZMZbxus4Q;
typedef NU8 tyEnum_GLFMColorFormat__nUNDU68er8APh3i5IGBrQw;
typedef NU8 tyEnum_GLFMDepthFormat__ht9aqGitR8QkJwdbpcyppwA;
typedef NU8 tyEnum_GLFMStencilFormat__s9bBkBlCzOH0vk5Yf3OCpNg;
typedef NU8 tyEnum_GLFMMultisample__nlYmaD9cZ4JEmzBJfgfMO8w;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void** display, int width, int height, void* ClE_0);
void* ClE_0;
} tyProc__KNiNOTQumxFz2O1GcNzZJw;
typedef N_CLOSURE_PTR(void, TM__zG6mA2D5kuOdfHNU9b6qlqQ_2) (void** display, int width, int height, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM__zG6mA2D5kuOdfHNU9b6qlqQ_3) (void** display, int width, int height, void* ClE_0);
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void** display, void* ClE_0);
void* ClE_0;
} tyProc__kAyOno27kR0x3SHsrIZCJg;
typedef N_CLOSURE_PTR(void, TM__zG6mA2D5kuOdfHNU9b6qlqQ_4) (void** display, void* ClE_0);
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void** display, double frameTime, void* ClE_0);
void* ClE_0;
} tyProc__l6Br0mXghIMqU7Ht2wXupA;
typedef N_CLOSURE_PTR(void, TM__zG6mA2D5kuOdfHNU9b6qlqQ_5) (void** display, double frameTime, void* ClE_0);
typedef NU8 tyEnum_GLFMTouchPhase__GpIScK4l6I2acWGc9czJhrg;
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (void** display, int touch, tyEnum_GLFMTouchPhase__GpIScK4l6I2acWGc9czJhrg phase, double x, double y, void* ClE_0);
void* ClE_0;
} tyProc__gIXK8VFKt9bDKmulNgQkBsQ;
typedef N_CLOSURE_PTR(NIM_BOOL, TM__zG6mA2D5kuOdfHNU9b6qlqQ_6) (void** display, int touch, tyEnum_GLFMTouchPhase__GpIScK4l6I2acWGc9czJhrg phase, double x, double y, void* ClE_0);
typedef NU16 tyEnum_GLFMKey__DYBF2avdaFQVSDz063lKrQ;
typedef NU8 tyEnum_GLFMKeyAction__dF5XKgm9b7rwfeDcf1UydiA;
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (void** display, tyEnum_GLFMKey__DYBF2avdaFQVSDz063lKrQ keyCode, tyEnum_GLFMKeyAction__dF5XKgm9b7rwfeDcf1UydiA action, int modifiers, void* ClE_0);
void* ClE_0;
} tyProc__uOgf9cK9bYdCzJtU4ddQIH9aQ;
typedef N_CLOSURE_PTR(NIM_BOOL, TM__zG6mA2D5kuOdfHNU9b6qlqQ_7) (void** display, tyEnum_GLFMKey__DYBF2avdaFQVSDz063lKrQ keyCode, tyEnum_GLFMKeyAction__dF5XKgm9b7rwfeDcf1UydiA action, int modifiers, void* ClE_0);
struct NimStrPayload {
NI cap;
AllocatorObj* allocator;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct TNimType {
void* destructor;
NI size;
NCSTRING name;
};
struct RootObj {
TNimType* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
NU raiseId;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc__NT9bSe2DDkjdtx7j9aov2Z6g;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc__NT9bSe2DDkjdtx7j9aov2Z6g raiseAction;
};
typedef NimStringV2 tyArray__sMpvt1sOxOJ3LFGulnbeMQ[4];
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ {
  NI len; tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content* p;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef NCSTRING tyArray__NmEsK2qSxmxyFA4fWeYieg[1];
typedef NimStringV2 tyArray__Re75IspeoxXy2oCZHwcRrA[2];
typedef N_NIMCALL_PTR(void*, tyProc__g4DU8Xso7TeLfKjjMA54hg) (AllocatorObj* a, NI size, NI alignment);
typedef N_NIMCALL_PTR(void, tyProc__f0fmYWZ9bBl5n2coKW0dYBQ) (AllocatorObj* a, void* p, NI size);
typedef N_NIMCALL_PTR(void*, tyProc__pc9bof8Viqlm9byLAeLaBy4g) (AllocatorObj* a, void* p, NI oldSize, NI newSize);
typedef N_NIMCALL_PTR(void, tyProc__up7108S0Kt9cUg781lCWRSQ) (AllocatorObj* a);
typedef NU8 tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg;
struct AllocatorObj {
TNimType* m_type;
tyProc__g4DU8Xso7TeLfKjjMA54hg alloc;
tyProc__f0fmYWZ9bBl5n2coKW0dYBQ dealloc;
tyProc__pc9bof8Viqlm9byLAeLaBy4g realloc;
tyProc__up7108S0Kt9cUg781lCWRSQ deallocAll;
tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg flags;
NCSTRING name;
NI allocCount;
NI deallocCount;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap;AllocatorObj* allocator;tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content_PP
#define tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content_PP
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content { NI cap;AllocatorObj* allocator;NF32 data[SEQ_DECL_SIZE];};
#endif

      N_NIMCALL(void, glfmMain)(void** display);
N_NIMCALL(void, glfmSetDisplayConfig)(void** display, tyEnum_GLFMRenderingAPI__89azhV1FN9ch7ehZMZbxus4Q preferredAPI, tyEnum_GLFMColorFormat__nUNDU68er8APh3i5IGBrQw colorFormat, tyEnum_GLFMDepthFormat__ht9aqGitR8QkJwdbpcyppwA depthFormat, tyEnum_GLFMStencilFormat__s9bBkBlCzOH0vk5Yf3OCpNg stencilFormat, tyEnum_GLFMMultisample__nlYmaD9cZ4JEmzBJfgfMO8w multisample);
N_NIMCALL(void, glfmSetUserData)(void** display, void* userData);
N_NIMCALL(void, glfmSetSurfaceCreatedFunc)(void** display, tyProc__KNiNOTQumxFz2O1GcNzZJw surfaceCreatedFunc);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
N_NIMCALL(void, glfmSetSurfaceResizedFunc)(void** display, tyProc__KNiNOTQumxFz2O1GcNzZJw surfaceResizedFunc);
N_NIMCALL(void, glfmSetSurfaceDestroyedFunc)(void** display, tyProc__kAyOno27kR0x3SHsrIZCJg surfaceDestroyedFunc);
N_NIMCALL(void, glfmSetMainLoopFunc)(void** display, tyProc__l6Br0mXghIMqU7Ht2wXupA mainLoopFunc);
N_NIMCALL(void, glfmSetTouchFunc)(void** display, tyProc__gIXK8VFKt9bDKmulNgQkBsQ touchFunc);
N_NIMCALL(void, glfmSetKeyFunc)(void** display, tyProc__uOgf9cK9bYdCzJtU4ddQIH9aQ keyFunc);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, onKey__uWY4nU4MQDfQof1Mqle7QA)(void** display, tyEnum_GLFMKey__DYBF2avdaFQVSDz063lKrQ keyCode, tyEnum_GLFMKeyAction__dF5XKgm9b7rwfeDcf1UydiA action, int modifiers);
static N_INLINE(void, minuseq___2gGQPdUypkoO8EiDQJwWdwsystem)(double* x, double y);
static N_INLINE(void, pluseq___2gGQPdUypkoO8EiDQJwWdw_2system)(double* x, double y);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, onTouch__6bNY2sUeizqXr9cS9aIO9aGzQ)(void** display, int touch, tyEnum_GLFMTouchPhase__GpIScK4l6I2acWGc9czJhrg phase, double x, double y);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_NIMCALL(void, glfmGetDisplaySize)(void** display, int* width, int* height);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
N_NIMCALL(NimStringV2, nimFloatToStr)(NF f);
N_NIMCALL(void, echoBinSafe)(NimStringV2* args, NI argsLen_0);
static N_INLINE(TFrame*, getFrame)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(void, onFrame__nRz4ZOTW09c3A0QTqlLjn1g)(void** display, double frameTime);
N_LIB_PRIVATE N_STDCALL(void, glClearColor__mRmvKpMRWVe0olxA2D6ibg)(NF32 red, NF32 green, NF32 blue, NF32 alpha);
N_LIB_PRIVATE N_STDCALL(void, glClear__bP2CTzt9boHsiXofCPEwKlw)(NU32 mask);
N_LIB_PRIVATE N_NIMCALL(NU32, compileShader__nayp9ceB4nTAT9a2FgcdT9aog)(NU32 type_0, NimStringV2 shaderString);
N_LIB_PRIVATE N_STDCALL(NU32, glCreateShader__aJRhkMsONGw6YriVczeVXw)(NU32 type_0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_STDCALL(void, glShaderSource__aAChP39b9c74do2PBxq3lQ2w)(NU32 shader, NI32 count, NCSTRING* string, NI32* length);
N_LIB_PRIVATE N_STDCALL(void, glCompileShader__JXarxWIUYZC38YQw9bzOQOQ)(NU32 shader);
N_LIB_PRIVATE N_STDCALL(void, glGetShaderiv__7nfLUNau354MWYxYlFPRkQ)(NU32 shader, NU32 pname, NI32* params);
N_NIMCALL(NimStringV2, nimIntToStr)(NI x);
N_NIMCALL(NimStringV2, rawNewString)(NI cap);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_STDCALL(void, glGetShaderInfoLog__P49ccOMvJ0UTL619cwd54DAw)(NU32 shader, NI32 bufSize, NI32* length, NCSTRING infoLog);
N_LIB_PRIVATE N_STDCALL(void, glDeleteShader__JXarxWIUYZC38YQw9bzOQOQ_2)(NU32 shader);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readAssetFile__KxN9a7qmfFyH656Mbrc9cejA)(NimStringV2 filename);
N_NIMCALL(int, glfmReadFileSize)(NCSTRING filename);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringV2, mnewString)(NI len);
N_NIMCALL(int, glfmReadFileBuffer)(NCSTRING filename, NCSTRING buffer);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___yJsHZJi5NyaV7IUe8n2jhA)(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ* dest);
N_LIB_PRIVATE N_STDCALL(NU32, glCreateProgram__5U6O7XOWiz3Kro2j6K7fHg)(void);
N_LIB_PRIVATE N_STDCALL(void, glAttachShader__59cx9cQog6uHwSy9cvdhQccbw)(NU32 program, NU32 shader);
N_LIB_PRIVATE N_STDCALL(void, glBindAttribLocation__uRnkKx7xCCCMIm9bGBTjK9bw)(NU32 program, NU32 index, NCSTRING name);
N_LIB_PRIVATE N_STDCALL(void, glLinkProgram__VmBV9c0dEsSOFA4kB5FAiVw)(NU32 program);
N_LIB_PRIVATE N_STDCALL(void, glUseProgram__VmBV9c0dEsSOFA4kB5FAiVw_2)(NU32 program);
N_LIB_PRIVATE N_STDCALL(void, glGenBuffers__aY0U7QWUPiGqN6yoXyh0iw)(NI32 n, NU32* buffers);
N_LIB_PRIVATE N_STDCALL(void, glBindBuffer__WUKuVaNXamgrBpVZ9bAUV9cA)(NU32 target, NU32 buffer);
N_LIB_PRIVATE N_STDCALL(void, glEnableVertexAttribArray__L4zGXkv7mX9cYBOWvb4Jlrg)(NU32 index);
N_LIB_PRIVATE N_STDCALL(void, glVertexAttribPointer__vD9cW9bmh7DJKgusHwHNi9byw)(NU32 index, NI32 size, NU32 type_0, NIM_BOOL normalized, NI32 stride, void* pointer);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___yGF9atWloxI3sbCEvYfmYRg)(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ* dest, tySequence__4Xyxy0Om14N6K1l5e9bUPSQ src);
N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize);
N_LIB_PRIVATE N_STDCALL(void, glBufferData__VLz8e7mQdBq50nh4P9btjaA)(NU32 target, NI size, void* data, NU32 usage);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_STDCALL(void, glDrawArrays__4aN8a5dpLSl7We9cWglkQeA)(NU32 mode, NI32 first, NI32 count);
N_LIB_PRIVATE N_NIMCALL(void, onSurfaceDestroyed__E0JR0pa1d9akOk9bu33whmXg)(void** display);
N_LIB_PRIVATE N_NIMCALL(void, onSurfaceCreated__fT1qrsV9c8l9b5cg8wJH9cAIw)(void** display, int width, int height);
N_LIB_PRIVATE N_STDCALL(void, glViewport__d738gxwcyV6Jhkv9aL2fVlQ)(NI32 x, NI32 y, NI32 width, NI32 height);
N_NIMCALL(tyEnum_GLFMRenderingAPI__89azhV1FN9ch7ehZMZbxus4Q, glfmGetRenderingAPI)(void** display);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_allocatorsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_allocatorsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, opengl_openglDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, opengl_openglInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
tyObject_ExampleApp__wvlZowQbd9bpaVzqNaWWC0Q app__M2vMrSonZ7OWYIO9cEHfowg;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
static const struct {
  NI cap; void* allocator; NIM_CHAR data[5+1];
} TM__zG6mA2D5kuOdfHNU9b6qlqQ_9 = { 5, NIM_NIL, "touch" };
static const NimStringV2 TM__zG6mA2D5kuOdfHNU9b6qlqQ_10 = {5, (NimStrPayload*)&TM__zG6mA2D5kuOdfHNU9b6qlqQ_9};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[1+1];
} TM__zG6mA2D5kuOdfHNU9b6qlqQ_11 = { 1, NIM_NIL, " " };
static const NimStringV2 TM__zG6mA2D5kuOdfHNU9b6qlqQ_12 = {1, (NimStrPayload*)&TM__zG6mA2D5kuOdfHNU9b6qlqQ_11};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[5+1];
} TM__zG6mA2D5kuOdfHNU9b6qlqQ_15 = { 5, NIM_NIL, "setup" };
NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__zG6mA2D5kuOdfHNU9b6qlqQ_14 = {{5, (NimStrPayload*)&TM__zG6mA2D5kuOdfHNU9b6qlqQ_15}}
;
static const struct {
  NI cap; void* allocator; NIM_CHAR data[17+1];
} TM__zG6mA2D5kuOdfHNU9b6qlqQ_18 = { 17, NIM_NIL, "glShaderSource..." };
NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__zG6mA2D5kuOdfHNU9b6qlqQ_17 = {{17, (NimStrPayload*)&TM__zG6mA2D5kuOdfHNU9b6qlqQ_18}}
;
static const struct {
  NI cap; void* allocator; NIM_CHAR data[18+1];
} TM__zG6mA2D5kuOdfHNU9b6qlqQ_20 = { 18, NIM_NIL, "glCompileShader..." };
NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__zG6mA2D5kuOdfHNU9b6qlqQ_19 = {{18, (NimStrPayload*)&TM__zG6mA2D5kuOdfHNU9b6qlqQ_20}}
;
static const struct {
  NI cap; void* allocator; NIM_CHAR data[29+1];
} TM__zG6mA2D5kuOdfHNU9b6qlqQ_22 = { 29, NIM_NIL, "So... Couldn\'t compile shader" };
NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__zG6mA2D5kuOdfHNU9b6qlqQ_21 = {{29, (NimStrPayload*)&TM__zG6mA2D5kuOdfHNU9b6qlqQ_22}}
;
static const struct {
  NI cap; void* allocator; NIM_CHAR data[32+1];
} TM__zG6mA2D5kuOdfHNU9b6qlqQ_24 = { 32, NIM_NIL, "glGetShaderiv GL_INFO_LOG_LENGTH" };
NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__zG6mA2D5kuOdfHNU9b6qlqQ_23 = {{32, (NimStrPayload*)&TM__zG6mA2D5kuOdfHNU9b6qlqQ_24}}
;
static const struct {
  NI cap; void* allocator; NIM_CHAR data[10+1];
} TM__zG6mA2D5kuOdfHNU9b6qlqQ_25 = { 10, NIM_NIL, "Log lengh " };
static const NimStringV2 TM__zG6mA2D5kuOdfHNU9b6qlqQ_26 = {10, (NimStrPayload*)&TM__zG6mA2D5kuOdfHNU9b6qlqQ_25};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[12+1];
} TM__zG6mA2D5kuOdfHNU9b6qlqQ_27 = { 12, NIM_NIL, "Shader log: " };
static const NimStringV2 TM__zG6mA2D5kuOdfHNU9b6qlqQ_28 = {12, (NimStrPayload*)&TM__zG6mA2D5kuOdfHNU9b6qlqQ_27};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[7+1];
} TM__zG6mA2D5kuOdfHNU9b6qlqQ_30 = { 7, NIM_NIL, "assets/" };
static const NimStringV2 TM__zG6mA2D5kuOdfHNU9b6qlqQ_31 = {7, (NimStrPayload*)&TM__zG6mA2D5kuOdfHNU9b6qlqQ_30};
static const NimStringV2 TM__zG6mA2D5kuOdfHNU9b6qlqQ_34 = {7, (NimStrPayload*)&TM__zG6mA2D5kuOdfHNU9b6qlqQ_30};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[11+1];
} TM__zG6mA2D5kuOdfHNU9b6qlqQ_35 = { 11, NIM_NIL, "simple.vert" };
static const NimStringV2 TM__zG6mA2D5kuOdfHNU9b6qlqQ_36 = {11, (NimStrPayload*)&TM__zG6mA2D5kuOdfHNU9b6qlqQ_35};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[11+1];
} TM__zG6mA2D5kuOdfHNU9b6qlqQ_37 = { 11, NIM_NIL, "simple.frag" };
static const NimStringV2 TM__zG6mA2D5kuOdfHNU9b6qlqQ_38 = {11, (NimStrPayload*)&TM__zG6mA2D5kuOdfHNU9b6qlqQ_37};
static NIM_CONST tyProc__l6Br0mXghIMqU7Ht2wXupA TM__zG6mA2D5kuOdfHNU9b6qlqQ_39 = {NIM_NIL,NIM_NIL};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[10+1];
} TM__zG6mA2D5kuOdfHNU9b6qlqQ_41 = { 10, NIM_NIL, "setup done" };
NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__zG6mA2D5kuOdfHNU9b6qlqQ_40 = {{10, (NimStrPayload*)&TM__zG6mA2D5kuOdfHNU9b6qlqQ_41}}
;

static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}

static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA9_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, glfmMain)(void** display) {
	tyProc__KNiNOTQumxFz2O1GcNzZJw T1_;
	tyProc__KNiNOTQumxFz2O1GcNzZJw T2_;
	tyProc__kAyOno27kR0x3SHsrIZCJg T3_;
	tyProc__l6Br0mXghIMqU7Ht2wXupA T4_;
	tyProc__gIXK8VFKt9bDKmulNgQkBsQ T5_;
	tyProc__uOgf9cK9bYdCzJtU4ddQIH9aQ T6_;
	nimfr_("glfmMain", "/p/glfm/examples/main.nim");
	nimln_(33, "/p/glfm/examples/main.nim");
	glfmSetDisplayConfig(display, ((tyEnum_GLFMRenderingAPI__89azhV1FN9ch7ehZMZbxus4Q) 0), ((tyEnum_GLFMColorFormat__nUNDU68er8APh3i5IGBrQw) 0), ((tyEnum_GLFMDepthFormat__ht9aqGitR8QkJwdbpcyppwA) 0), ((tyEnum_GLFMStencilFormat__s9bBkBlCzOH0vk5Yf3OCpNg) 0), ((tyEnum_GLFMMultisample__nlYmaD9cZ4JEmzBJfgfMO8w) 0));
	nimln_(36, "/p/glfm/examples/main.nim");
	glfmSetUserData(display, ((void*) ((&app__M2vMrSonZ7OWYIO9cEHfowg))));
	nimln_(37, "/p/glfm/examples/main.nim");
	nimZeroMem((void*)(&T1_), sizeof(tyProc__KNiNOTQumxFz2O1GcNzZJw));
	T1_.ClP_0 = ((TM__zG6mA2D5kuOdfHNU9b6qlqQ_2) (onSurfaceCreated__fT1qrsV9c8l9b5cg8wJH9cAIw)); T1_.ClE_0 = NIM_NIL;
	glfmSetSurfaceCreatedFunc(display, T1_);
	nimln_(38, "/p/glfm/examples/main.nim");
	nimZeroMem((void*)(&T2_), sizeof(tyProc__KNiNOTQumxFz2O1GcNzZJw));
	T2_.ClP_0 = ((TM__zG6mA2D5kuOdfHNU9b6qlqQ_3) (onSurfaceCreated__fT1qrsV9c8l9b5cg8wJH9cAIw)); T2_.ClE_0 = NIM_NIL;
	glfmSetSurfaceResizedFunc(display, T2_);
	nimln_(39, "/p/glfm/examples/main.nim");
	nimZeroMem((void*)(&T3_), sizeof(tyProc__kAyOno27kR0x3SHsrIZCJg));
	T3_.ClP_0 = ((TM__zG6mA2D5kuOdfHNU9b6qlqQ_4) (onSurfaceDestroyed__E0JR0pa1d9akOk9bu33whmXg)); T3_.ClE_0 = NIM_NIL;
	glfmSetSurfaceDestroyedFunc(display, T3_);
	nimln_(40, "/p/glfm/examples/main.nim");
	nimZeroMem((void*)(&T4_), sizeof(tyProc__l6Br0mXghIMqU7Ht2wXupA));
	T4_.ClP_0 = ((TM__zG6mA2D5kuOdfHNU9b6qlqQ_5) (onFrame__nRz4ZOTW09c3A0QTqlLjn1g)); T4_.ClE_0 = NIM_NIL;
	glfmSetMainLoopFunc(display, T4_);
	nimln_(41, "/p/glfm/examples/main.nim");
	nimZeroMem((void*)(&T5_), sizeof(tyProc__gIXK8VFKt9bDKmulNgQkBsQ));
	T5_.ClP_0 = ((TM__zG6mA2D5kuOdfHNU9b6qlqQ_6) (onTouch__6bNY2sUeizqXr9cS9aIO9aGzQ)); T5_.ClE_0 = NIM_NIL;
	glfmSetTouchFunc(display, T5_);
	nimln_(42, "/p/glfm/examples/main.nim");
	nimZeroMem((void*)(&T6_), sizeof(tyProc__uOgf9cK9bYdCzJtU4ddQIH9aQ));
	T6_.ClP_0 = ((TM__zG6mA2D5kuOdfHNU9b6qlqQ_7) (onKey__uWY4nU4MQDfQof1Mqle7QA)); T6_.ClE_0 = NIM_NIL;
	glfmSetKeyFunc(display, T6_);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
}

static N_INLINE(void, minuseq___2gGQPdUypkoO8EiDQJwWdwsystem)(double* x, double y) {
	nimfr_("-=", "/p/Nim/lib/system.nim");
	nimln_(4130, "/p/Nim/lib/system.nim");
	(*x) = ((NF)((*x)) - (NF)(y));
	popFrame();
}

static N_INLINE(void, pluseq___2gGQPdUypkoO8EiDQJwWdw_2system)(double* x, double y) {
	nimfr_("+=", "/p/Nim/lib/system.nim");
	nimln_(4125, "/p/Nim/lib/system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, onKey__uWY4nU4MQDfQof1Mqle7QA)(void** display, tyEnum_GLFMKey__DYBF2avdaFQVSDz063lKrQ keyCode, tyEnum_GLFMKeyAction__dF5XKgm9b7rwfeDcf1UydiA action, int modifiers) {
	NIM_BOOL result;
	NIM_BOOL handled;
	nimfr_("onKey", "/p/glfm/examples/main.nim");
{	result = (NIM_BOOL)0;
	nimln_(68, "/p/glfm/examples/main.nim");
	handled = NIM_FALSE;
	nimln_(69, "/p/glfm/examples/main.nim");
	{
		if (!(action == ((tyEnum_GLFMKeyAction__dF5XKgm9b7rwfeDcf1UydiA) 0))) goto LA3_;
		nimln_(71, "/p/glfm/examples/main.nim");
		switch (keyCode) {
		case ((tyEnum_GLFMKey__DYBF2avdaFQVSDz063lKrQ) 37):
		{
			nimln_(73, "/p/glfm/examples/main.nim");
			minuseq___2gGQPdUypkoO8EiDQJwWdwsystem((&app__M2vMrSonZ7OWYIO9cEHfowg.offsetX), 1.0000000000000001e-01);
			nimln_(74, "/p/glfm/examples/main.nim");
			handled = NIM_TRUE;
		}
		break;
		case ((tyEnum_GLFMKey__DYBF2avdaFQVSDz063lKrQ) 39):
		{
			nimln_(76, "/p/glfm/examples/main.nim");
			pluseq___2gGQPdUypkoO8EiDQJwWdw_2system((&app__M2vMrSonZ7OWYIO9cEHfowg.offsetX), 1.0000000000000001e-01);
			nimln_(77, "/p/glfm/examples/main.nim");
			handled = NIM_TRUE;
		}
		break;
		case ((tyEnum_GLFMKey__DYBF2avdaFQVSDz063lKrQ) 38):
		{
			nimln_(79, "/p/glfm/examples/main.nim");
			minuseq___2gGQPdUypkoO8EiDQJwWdwsystem((&app__M2vMrSonZ7OWYIO9cEHfowg.offsetY), 1.0000000000000001e-01);
			nimln_(80, "/p/glfm/examples/main.nim");
			handled = NIM_TRUE;
		}
		break;
		case ((tyEnum_GLFMKey__DYBF2avdaFQVSDz063lKrQ) 40):
		{
			nimln_(82, "/p/glfm/examples/main.nim");
			pluseq___2gGQPdUypkoO8EiDQJwWdw_2system((&app__M2vMrSonZ7OWYIO9cEHfowg.offsetY), 1.0000000000000001e-01);
			nimln_(83, "/p/glfm/examples/main.nim");
			handled = NIM_TRUE;
		}
		break;
		default:
		{
		}
		break;
		}
	}
	LA3_: ;
	nimln_(86, "/p/glfm/examples/main.nim");
	result = handled;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler__rqLlY5bs9atDw2OXYqJEn5g;
	excHandler__rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler__rqLlY5bs9atDw2OXYqJEn5g = (*excHandler__rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(TFrame*, getFrame)(void) {
	TFrame* result;
	result = (TFrame*)0;
	result = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	return result;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, onTouch__6bNY2sUeizqXr9cS9aIO9aGzQ)(void** display, int touch, tyEnum_GLFMTouchPhase__GpIScK4l6I2acWGc9czJhrg phase, double x, double y) {
	NIM_BOOL result;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	TSafePoint TM__zG6mA2D5kuOdfHNU9b6qlqQ_8;
	TFrame* _nimCurFrame;
	nimfr_("onTouch", "/p/glfm/examples/main.nim");
{	_nimCurFrame = getFrame();
	result = (NIM_BOOL)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimln_(46, "/p/glfm/examples/main.nim");
	pushSafePoint(&TM__zG6mA2D5kuOdfHNU9b6qlqQ_8);
	TM__zG6mA2D5kuOdfHNU9b6qlqQ_8.status = setjmp(TM__zG6mA2D5kuOdfHNU9b6qlqQ_8.context);
	if (TM__zG6mA2D5kuOdfHNU9b6qlqQ_8.status == 0) {
		{
			if (!(phase == ((tyEnum_GLFMTouchPhase__GpIScK4l6I2acWGc9czJhrg) 0))) goto LA4_;
			nimln_(47, "/p/glfm/examples/main.nim");
			result = NIM_FALSE;
			popSafePoint();
			nimln_(34, "/p/Nim/lib/system/fatal.nim");
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
			goto BeforeRet_;
		}
		LA4_: ;
		nimln_(49, "/p/glfm/examples/main.nim");
		{
			int width;
			int height;
			tyArray__sMpvt1sOxOJ3LFGulnbeMQ T10_;
			NimStringV2 T11_;
			NimStringV2 T12_;
			if (!!((phase == ((tyEnum_GLFMTouchPhase__GpIScK4l6I2acWGc9czJhrg) 1)))) goto LA8_;
			width = (int)0;
			height = (int)0;
			nimln_(53, "/p/glfm/examples/main.nim");
			glfmGetDisplaySize(display, (&width), (&height));
			nimln_(55, "/p/glfm/examples/main.nim");
			pluseq___2gGQPdUypkoO8EiDQJwWdw_2system((&app__M2vMrSonZ7OWYIO9cEHfowg.offsetX), ((NF)(((NF)(2.0000000000000000e+00) * (NF)(((NF)(x) - (NF)(app__M2vMrSonZ7OWYIO9cEHfowg.lastTouchX))))) / (NF)(((NF) (width)))));
			nimln_(57, "/p/glfm/examples/main.nim");
			minuseq___2gGQPdUypkoO8EiDQJwWdwsystem((&app__M2vMrSonZ7OWYIO9cEHfowg.offsetY), ((NF)(((NF)(2.0000000000000000e+00) * (NF)(((NF)(y) - (NF)(app__M2vMrSonZ7OWYIO9cEHfowg.lastTouchY))))) / (NF)(((NF) (height)))));
			nimln_(59, "/p/glfm/examples/main.nim");
			T10_[0] = TM__zG6mA2D5kuOdfHNU9b6qlqQ_10;
			nimln_(34, "/p/Nim/lib/system/fatal.nim");
			nimln_(59, "/p/glfm/examples/main.nim");
			T11_.len = 0; T11_.p = NIM_NIL;
			T11_ = nimFloatToStr(app__M2vMrSonZ7OWYIO9cEHfowg.offsetX);
			nimln_(34, "/p/Nim/lib/system/fatal.nim");
			eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T11_);
			T10_[1] = colontmpD_;
			T10_[2] = TM__zG6mA2D5kuOdfHNU9b6qlqQ_12;
			nimln_(59, "/p/glfm/examples/main.nim");
			T12_.len = 0; T12_.p = NIM_NIL;
			T12_ = nimFloatToStr(app__M2vMrSonZ7OWYIO9cEHfowg.offsetY);
			nimln_(34, "/p/Nim/lib/system/fatal.nim");
			eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__2), T12_);
			T10_[3] = colontmpD__2;
			echoBinSafe(T10_, 4);
		}
		LA8_: ;
		nimln_(62, "/p/glfm/examples/main.nim");
		app__M2vMrSonZ7OWYIO9cEHfowg.lastTouchX = x;
		nimln_(63, "/p/glfm/examples/main.nim");
		app__M2vMrSonZ7OWYIO9cEHfowg.lastTouchY = y;
		nimln_(64, "/p/glfm/examples/main.nim");
		result = NIM_TRUE;
		popSafePoint();
		nimln_(34, "/p/Nim/lib/system/fatal.nim");
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
		goto BeforeRet_;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame(_nimCurFrame);
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}
	if (TM__zG6mA2D5kuOdfHNU9b6qlqQ_8.status != 0) reraiseException();
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		if (!(s.len == ((NI) 0))) goto LA3_;
		result = "";
	}
	goto LA1_;
	LA3_: ;
	{
		result = ((NCSTRING) ((*s.p).data));
	}
	LA1_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU32, compileShader__nayp9ceB4nTAT9a2FgcdT9aog)(NU32 type_0, NimStringV2 shaderString) {
	NU32 result;
	NimStringV2 colontmpD_;
	NimStringV2 log;
	TSafePoint TM__zG6mA2D5kuOdfHNU9b6qlqQ_16;
	TFrame* _nimCurFrame;
	nimfr_("compileShader", "/p/glfm/examples/main.nim");
{	_nimCurFrame = getFrame();
	result = (NU32)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	log.len = 0; log.p = NIM_NIL;
	nimln_(123, "/p/glfm/examples/main.nim");
	pushSafePoint(&TM__zG6mA2D5kuOdfHNU9b6qlqQ_16);
	TM__zG6mA2D5kuOdfHNU9b6qlqQ_16.status = setjmp(TM__zG6mA2D5kuOdfHNU9b6qlqQ_16.context);
	if (TM__zG6mA2D5kuOdfHNU9b6qlqQ_16.status == 0) {
		NU32 shader;
		tyArray__NmEsK2qSxmxyFA4fWeYieg shaderTextArr;
		NI32 status;
		shader = glCreateShader__aJRhkMsONGw6YriVczeVXw(type_0);
		nimZeroMem((void*)shaderTextArr, sizeof(tyArray__NmEsK2qSxmxyFA4fWeYieg));
		nimln_(124, "/p/glfm/examples/main.nim");
		shaderTextArr[0] = nimToCStringConv(shaderString);
		nimln_(125, "/p/glfm/examples/main.nim");
		echoBinSafe(TM__zG6mA2D5kuOdfHNU9b6qlqQ_17, 1);
		nimln_(126, "/p/glfm/examples/main.nim");
		glShaderSource__aAChP39b9c74do2PBxq3lQ2w(shader, ((NI32) 1), ((NCSTRING*) (shaderTextArr)), NIM_NIL);
		nimln_(127, "/p/glfm/examples/main.nim");
		echoBinSafe(TM__zG6mA2D5kuOdfHNU9b6qlqQ_19, 1);
		nimln_(128, "/p/glfm/examples/main.nim");
		glCompileShader__JXarxWIUYZC38YQw9bzOQOQ(shader);
		status = (NI32)0;
		nimln_(133, "/p/glfm/examples/main.nim");
		glGetShaderiv__7nfLUNau354MWYxYlFPRkQ(shader, ((NU32) 35713), (&status));
		nimln_(134, "/p/glfm/examples/main.nim");
		{
			NI32 logLength;
			tyArray__Re75IspeoxXy2oCZHwcRrA T6_;
			NimStringV2 T7_;
			if (!(status == ((NI32) 0))) goto LA4_;
			nimln_(135, "/p/glfm/examples/main.nim");
			echoBinSafe(TM__zG6mA2D5kuOdfHNU9b6qlqQ_21, 1);
			logLength = (NI32)0;
			nimln_(137, "/p/glfm/examples/main.nim");
			echoBinSafe(TM__zG6mA2D5kuOdfHNU9b6qlqQ_23, 1);
			nimln_(138, "/p/glfm/examples/main.nim");
			glGetShaderiv__7nfLUNau354MWYxYlFPRkQ(shader, ((NU32) 35716), (&logLength));
			nimln_(139, "/p/glfm/examples/main.nim");
			T6_[0] = TM__zG6mA2D5kuOdfHNU9b6qlqQ_26;
			nimln_(34, "/p/Nim/lib/system/fatal.nim");
			nimln_(139, "/p/glfm/examples/main.nim");
			T7_.len = 0; T7_.p = NIM_NIL;
			T7_ = nimIntToStr(((NI) (logLength)));
			nimln_(34, "/p/Nim/lib/system/fatal.nim");
			eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T7_);
			T6_[1] = colontmpD_;
			echoBinSafe(T6_, 2);
			nimln_(140, "/p/glfm/examples/main.nim");
			{
				NimStringV2 T12_;
				tyArray__Re75IspeoxXy2oCZHwcRrA T13_;
				if (!(((NI32) 0) < logLength)) goto LA10_;
				nimln_(34, "/p/Nim/lib/system/fatal.nim");
				nimln_(141, "/p/glfm/examples/main.nim");
				T12_.len = 0; T12_.p = NIM_NIL;
				T12_ = rawNewString(((NI)chckRange(logLength, ((NI) 0), ((NI) IL64(9223372036854775807)))));
				nimln_(34, "/p/Nim/lib/system/fatal.nim");
				eqsink___aBBXmHFBEivKqERloP6zmA((&log), T12_);
				nimln_(142, "/p/glfm/examples/main.nim");
				glGetShaderInfoLog__P49ccOMvJ0UTL619cwd54DAw(shader, logLength, (&logLength), nimToCStringConv(log));
				nimln_(143, "/p/glfm/examples/main.nim");
				T13_[0] = TM__zG6mA2D5kuOdfHNU9b6qlqQ_28;
				T13_[1] = log;
				echoBinSafe(T13_, 2);
			}
			LA10_: ;
			nimln_(144, "/p/glfm/examples/main.nim");
			glDeleteShader__JXarxWIUYZC38YQw9bzOQOQ_2(shader);
			nimln_(145, "/p/glfm/examples/main.nim");
			shader = ((NU32) 0);
		}
		LA4_: ;
		nimln_(146, "/p/glfm/examples/main.nim");
		result = shader;
		popSafePoint();
		nimln_(34, "/p/Nim/lib/system/fatal.nim");
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&log));
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
		goto BeforeRet_;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame(_nimCurFrame);
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&log));
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}
	if (TM__zG6mA2D5kuOdfHNU9b6qlqQ_16.status != 0) reraiseException();
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {
	{
		NI TM__zG6mA2D5kuOdfHNU9b6qlqQ_32;
		NI TM__zG6mA2D5kuOdfHNU9b6qlqQ_33;
		if (!(((NI) 0) < src.len)) goto LA3_;
		TM__zG6mA2D5kuOdfHNU9b6qlqQ_32 = addInt(src.len, ((NI) 1));
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI)chckRange((NI)(TM__zG6mA2D5kuOdfHNU9b6qlqQ_32), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		TM__zG6mA2D5kuOdfHNU9b6qlqQ_33 = addInt((*dest).len, src.len);
		(*dest).len = (NI)(TM__zG6mA2D5kuOdfHNU9b6qlqQ_33);
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(NimStringV2, readAssetFile__KxN9a7qmfFyH656Mbrc9cejA)(NimStringV2 filename) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	TSafePoint TM__zG6mA2D5kuOdfHNU9b6qlqQ_29;
	TFrame* _nimCurFrame;
	nimfr_("readAssetFile", "/p/glfm/examples/main.nim");
	_nimCurFrame = getFrame();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimln_(153, "/p/glfm/examples/main.nim");
	pushSafePoint(&TM__zG6mA2D5kuOdfHNU9b6qlqQ_29);
	TM__zG6mA2D5kuOdfHNU9b6qlqQ_29.status = setjmp(TM__zG6mA2D5kuOdfHNU9b6qlqQ_29.context);
	if (TM__zG6mA2D5kuOdfHNU9b6qlqQ_29.status == 0) {
		NI size;
		NimStringV2 T2_;
		int T3_;
		NimStringV2 T4_;
		NimStringV2 T5_;
		int T6_;
		nimln_(34, "/p/Nim/lib/system/fatal.nim");
		nimln_(153, "/p/glfm/examples/main.nim");
		T2_.len = 0; T2_.p = NIM_NIL;
		T2_ = rawNewString(filename.len + 7);
appendString((&T2_), TM__zG6mA2D5kuOdfHNU9b6qlqQ_31);
appendString((&T2_), filename);
		nimln_(34, "/p/Nim/lib/system/fatal.nim");
		eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T2_);
		nimln_(153, "/p/glfm/examples/main.nim");
		T3_ = (int)0;
		T3_ = glfmReadFileSize(nimToCStringConv(colontmpD_));
		size = ((NI) (T3_));
		nimln_(34, "/p/Nim/lib/system/fatal.nim");
		nimln_(154, "/p/glfm/examples/main.nim");
		T4_.len = 0; T4_.p = NIM_NIL;
		T4_ = mnewString(((NI)chckRange(size, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln_(34, "/p/Nim/lib/system/fatal.nim");
		eqsink___aBBXmHFBEivKqERloP6zmA((&result), T4_);
		nimln_(155, "/p/glfm/examples/main.nim");
		nimln_(34, "/p/Nim/lib/system/fatal.nim");
		nimln_(155, "/p/glfm/examples/main.nim");
		T5_.len = 0; T5_.p = NIM_NIL;
		T5_ = rawNewString(filename.len + 7);
appendString((&T5_), TM__zG6mA2D5kuOdfHNU9b6qlqQ_34);
appendString((&T5_), filename);
		nimln_(34, "/p/Nim/lib/system/fatal.nim");
		eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__2), T5_);
		nimln_(155, "/p/glfm/examples/main.nim");
		T6_ = (int)0;
		T6_ = glfmReadFileBuffer(nimToCStringConv(colontmpD__2), nimToCStringConv(result));
		(void)(T6_);
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame(_nimCurFrame);
	}
	{
		nimln_(34, "/p/Nim/lib/system/fatal.nim");
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}
	if (TM__zG6mA2D5kuOdfHNU9b6qlqQ_29.status != 0) reraiseException();
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, onFrame__nRz4ZOTW09c3A0QTqlLjn1g)(void** display, double frameTime) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ vertices;
	TSafePoint TM__zG6mA2D5kuOdfHNU9b6qlqQ_13;
	TFrame* _nimCurFrame;
	nimfr_("onFrame", "/p/glfm/examples/main.nim");
{	_nimCurFrame = getFrame();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	vertices.len = 0; vertices.p = NIM_NIL;
	nimln_(160, "/p/glfm/examples/main.nim");
	pushSafePoint(&TM__zG6mA2D5kuOdfHNU9b6qlqQ_13);
	TM__zG6mA2D5kuOdfHNU9b6qlqQ_13.status = setjmp(TM__zG6mA2D5kuOdfHNU9b6qlqQ_13.context);
	if (TM__zG6mA2D5kuOdfHNU9b6qlqQ_13.status == 0) {
		NI32 stride;
		tySequence__4Xyxy0Om14N6K1l5e9bUPSQ T18_;
		NI T19_;
		NI TM__zG6mA2D5kuOdfHNU9b6qlqQ_42;
		nimln_(161, "/p/glfm/examples/main.nim");
		glClearColor__mRmvKpMRWVe0olxA2D6ibg(0.0, 0.0, 0.0, 1.0000000000000000e+00);
		nimln_(162, "/p/glfm/examples/main.nim");
		glClear__bP2CTzt9boHsiXofCPEwKlw(((NU32) 16384));
		nimln_(164, "/p/glfm/examples/main.nim");
		{
			NU32 vertShader;
			NimStringV2 T6_;
			NU32 fragShader;
			NimStringV2 T7_;
			if (!(app__M2vMrSonZ7OWYIO9cEHfowg.program == ((NI) 0))) goto LA4_;
			nimln_(165, "/p/glfm/examples/main.nim");
			echoBinSafe(TM__zG6mA2D5kuOdfHNU9b6qlqQ_14, 1);
			nimln_(166, "/p/glfm/examples/main.nim");
			nimln_(34, "/p/Nim/lib/system/fatal.nim");
			nimln_(166, "/p/glfm/examples/main.nim");
			T6_.len = 0; T6_.p = NIM_NIL;
			T6_ = readAssetFile__KxN9a7qmfFyH656Mbrc9cejA(TM__zG6mA2D5kuOdfHNU9b6qlqQ_36);
			nimln_(34, "/p/Nim/lib/system/fatal.nim");
			eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T6_);
			nimln_(166, "/p/glfm/examples/main.nim");
			vertShader = compileShader__nayp9ceB4nTAT9a2FgcdT9aog(((NU32) 35633), colontmpD_);
			nimln_(167, "/p/glfm/examples/main.nim");
			nimln_(34, "/p/Nim/lib/system/fatal.nim");
			nimln_(167, "/p/glfm/examples/main.nim");
			T7_.len = 0; T7_.p = NIM_NIL;
			T7_ = readAssetFile__KxN9a7qmfFyH656Mbrc9cejA(TM__zG6mA2D5kuOdfHNU9b6qlqQ_38);
			nimln_(34, "/p/Nim/lib/system/fatal.nim");
			eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__2), T7_);
			nimln_(167, "/p/glfm/examples/main.nim");
			fragShader = compileShader__nayp9ceB4nTAT9a2FgcdT9aog(((NU32) 35632), colontmpD__2);
			nimln_(168, "/p/glfm/examples/main.nim");
			{
				NIM_BOOL T10_;
				T10_ = (NIM_BOOL)0;
				T10_ = (vertShader == ((NI) 0));
				if (T10_) goto LA11_;
				T10_ = (fragShader == ((NI) 0));
				LA11_: ;
				if (!T10_) goto LA12_;
				nimln_(169, "/p/glfm/examples/main.nim");
				glfmSetMainLoopFunc(display, TM__zG6mA2D5kuOdfHNU9b6qlqQ_39);
				nimln_(170, "/p/glfm/examples/main.nim");
				popSafePoint();
				nimln_(235, "/p/glfm/examples/main.nim");
				eqdestroy___yJsHZJi5NyaV7IUe8n2jhA((&vertices));
				nimln_(34, "/p/Nim/lib/system/fatal.nim");
				eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));
				eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
				goto BeforeRet_;
			}
			LA12_: ;
			nimln_(171, "/p/glfm/examples/main.nim");
			app__M2vMrSonZ7OWYIO9cEHfowg.program = glCreateProgram__5U6O7XOWiz3Kro2j6K7fHg();
			nimln_(172, "/p/glfm/examples/main.nim");
			glAttachShader__59cx9cQog6uHwSy9cvdhQccbw(app__M2vMrSonZ7OWYIO9cEHfowg.program, vertShader);
			nimln_(173, "/p/glfm/examples/main.nim");
			glAttachShader__59cx9cQog6uHwSy9cvdhQccbw(app__M2vMrSonZ7OWYIO9cEHfowg.program, fragShader);
			nimln_(174, "/p/glfm/examples/main.nim");
			glBindAttribLocation__uRnkKx7xCCCMIm9bGBTjK9bw(app__M2vMrSonZ7OWYIO9cEHfowg.program, ((NU32) 0), "a_position");
			nimln_(175, "/p/glfm/examples/main.nim");
			glBindAttribLocation__uRnkKx7xCCCMIm9bGBTjK9bw(app__M2vMrSonZ7OWYIO9cEHfowg.program, ((NU32) 1), "a_color");
			nimln_(176, "/p/glfm/examples/main.nim");
			glLinkProgram__VmBV9c0dEsSOFA4kB5FAiVw(app__M2vMrSonZ7OWYIO9cEHfowg.program);
			nimln_(177, "/p/glfm/examples/main.nim");
			glDeleteShader__JXarxWIUYZC38YQw9bzOQOQ_2(vertShader);
			nimln_(178, "/p/glfm/examples/main.nim");
			glDeleteShader__JXarxWIUYZC38YQw9bzOQOQ_2(fragShader);
			nimln_(179, "/p/glfm/examples/main.nim");
			echoBinSafe(TM__zG6mA2D5kuOdfHNU9b6qlqQ_40, 1);
		}
		LA4_: ;
		nimln_(211, "/p/glfm/examples/main.nim");
		glUseProgram__VmBV9c0dEsSOFA4kB5FAiVw_2(app__M2vMrSonZ7OWYIO9cEHfowg.program);
		nimln_(213, "/p/glfm/examples/main.nim");
		{
			if (!(app__M2vMrSonZ7OWYIO9cEHfowg.vertexBuffer == ((NI) 0))) goto LA16_;
			nimln_(214, "/p/glfm/examples/main.nim");
			glGenBuffers__aY0U7QWUPiGqN6yoXyh0iw(((NI32) 1), (&app__M2vMrSonZ7OWYIO9cEHfowg.vertexBuffer));
		}
		LA16_: ;
		nimln_(216, "/p/glfm/examples/main.nim");
		glBindBuffer__WUKuVaNXamgrBpVZ9bAUV9cA(((NU32) 34962), app__M2vMrSonZ7OWYIO9cEHfowg.vertexBuffer);
		nimln_(217, "/p/glfm/examples/main.nim");
		stride = ((NI32) 24);
		nimln_(218, "/p/glfm/examples/main.nim");
		glEnableVertexAttribArray__L4zGXkv7mX9cYBOWvb4Jlrg(((NU32) 0));
		nimln_(219, "/p/glfm/examples/main.nim");
		glVertexAttribPointer__vD9cW9bmh7DJKgusHwHNi9byw(((NU32) 0), ((NI32) 3), ((NU32) 5126), NIM_FALSE, stride, ((void*) (((NI) 0))));
		nimln_(220, "/p/glfm/examples/main.nim");
		glEnableVertexAttribArray__L4zGXkv7mX9cYBOWvb4Jlrg(((NU32) 1));
		nimln_(221, "/p/glfm/examples/main.nim");
		glVertexAttribPointer__vD9cW9bmh7DJKgusHwHNi9byw(((NU32) 1), ((NI32) 3), ((NU32) 5126), NIM_FALSE, stride, ((void*) (((NI) 12))));
		nimln_(235, "/p/glfm/examples/main.nim");
		T18_.len = 0; T18_.p = NIM_NIL;
		T18_.len = 18; T18_.p = (tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content*) newSeqPayload(18, sizeof(NF32));
		nimln_(236, "/p/glfm/examples/main.nim");
		T18_.p->data[0] = ((NF32)(((NF32) (app__M2vMrSonZ7OWYIO9cEHfowg.offsetX))) + (NF32)(0.0));
		T18_.p->data[1] = ((NF32) (((NF)(((NF) (((NF32) (app__M2vMrSonZ7OWYIO9cEHfowg.offsetY))))) + (NF)(5.0000000000000000e-01))));
		T18_.p->data[2] = 0.0;
		T18_.p->data[3] = 1.0000000000000000e+00;
		T18_.p->data[4] = 0.0;
		T18_.p->data[5] = 0.0;
		nimln_(237, "/p/glfm/examples/main.nim");
		T18_.p->data[6] = ((NF32)(((NF32) (app__M2vMrSonZ7OWYIO9cEHfowg.offsetX))) - (NF32)(5.0000000000000000e-01));
		T18_.p->data[7] = ((NF32) (((NF)(((NF) (((NF32) (app__M2vMrSonZ7OWYIO9cEHfowg.offsetY))))) - (NF)(5.0000000000000000e-01))));
		T18_.p->data[8] = 0.0;
		T18_.p->data[9] = 0.0;
		T18_.p->data[10] = 1.0000000000000000e+00;
		T18_.p->data[11] = 0.0;
		nimln_(238, "/p/glfm/examples/main.nim");
		T18_.p->data[12] = ((NF32)(((NF32) (app__M2vMrSonZ7OWYIO9cEHfowg.offsetX))) + (NF32)(5.0000000000000000e-01));
		T18_.p->data[13] = ((NF32) (((NF)(((NF) (((NF32) (app__M2vMrSonZ7OWYIO9cEHfowg.offsetY))))) - (NF)(5.0000000000000000e-01))));
		T18_.p->data[14] = 0.0;
		T18_.p->data[15] = 0.0;
		T18_.p->data[16] = 0.0;
		T18_.p->data[17] = 1.0000000000000000e+00;
		nimln_(235, "/p/glfm/examples/main.nim");
		eqsink___yGF9atWloxI3sbCEvYfmYRg((&vertices), T18_);
		nimln_(247, "/p/glfm/examples/main.nim");
		T19_ = vertices.len;
		TM__zG6mA2D5kuOdfHNU9b6qlqQ_42 = mulInt(T19_, ((NI) 4));
		if ((NU)(((NI) 0)) >= (NU)vertices.len) raiseIndexError2(((NI) 0),vertices.len-1);
		glBufferData__VLz8e7mQdBq50nh4P9btjaA(((NU32) 34962), (NI)(TM__zG6mA2D5kuOdfHNU9b6qlqQ_42), ((void*) ((&vertices.p->data[((NI) 0)]))), ((NU32) 35044));
		nimln_(249, "/p/glfm/examples/main.nim");
		glDrawArrays__4aN8a5dpLSl7We9cWglkQeA(((NU32) 4), ((NI32) 0), ((NI32) 3));
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame(_nimCurFrame);
	}
	{
		nimln_(235, "/p/glfm/examples/main.nim");
		eqdestroy___yJsHZJi5NyaV7IUe8n2jhA((&vertices));
		nimln_(34, "/p/Nim/lib/system/fatal.nim");
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}
	if (TM__zG6mA2D5kuOdfHNU9b6qlqQ_13.status != 0) reraiseException();
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, onSurfaceDestroyed__E0JR0pa1d9akOk9bu33whmXg)(void** display) {
	nimfr_("onSurfaceDestroyed", "/p/glfm/examples/main.nim");
	nimln_(99, "/p/glfm/examples/main.nim");
	app__M2vMrSonZ7OWYIO9cEHfowg.program = ((NU32) 0);
	nimln_(100, "/p/glfm/examples/main.nim");
	app__M2vMrSonZ7OWYIO9cEHfowg.vertexBuffer = ((NU32) 0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, onSurfaceCreated__fT1qrsV9c8l9b5cg8wJH9cAIw)(void** display, int width, int height) {
	tyEnum_GLFMRenderingAPI__89azhV1FN9ch7ehZMZbxus4Q api;
	nimfr_("onSurfaceCreated", "/p/glfm/examples/main.nim");
	nimln_(89, "/p/glfm/examples/main.nim");
	glViewport__d738gxwcyV6Jhkv9aL2fVlQ(((NI32) 0), ((NI32) 0), width, height);
	nimln_(90, "/p/glfm/examples/main.nim");
	api = glfmGetRenderingAPI(display);
	popFrame();
}

void PreMainInner(void) {
	stdlib_allocatorsInit000();
	opengl_openglInit000();
}

int cmdCount;
char** cmdLine;
char** gEnv;
void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	stdlib_allocatorsDatInit000();
	systemDatInit000();
	initStackBottomWith((void *)&inner);
	systemInit000();
	opengl_openglDatInit000();
	(*inner)();
}

N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

