/* Generated by Nim Compiler v0.20.99 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStrPayload NimStrPayload;
typedef struct AllocatorObj AllocatorObj;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
NI cap;
AllocatorObj* allocator;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA9_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringV2 s, NimStringV2 prefix) {
	NIM_BOOL result;
	NI i;
	nimfr_("startsWith", "/p/Nim/lib/pure/strutils.nim");
{	result = (NIM_BOOL)0;
	nimln_(1537, "/p/Nim/lib/pure/strutils.nim");
	i = ((NI) 0);
	{
		nimln_(1538, "/p/Nim/lib/pure/strutils.nim");
		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_2;
			nimln_(1539, "/p/Nim/lib/pure/strutils.nim");
			{
				if (!(prefix.len <= i)) goto LA5_;
				result = NIM_TRUE;
				goto BeforeRet_;
			}
			LA5_: ;
			nimln_(1540, "/p/Nim/lib/pure/strutils.nim");
			{
				NIM_BOOL T9_;
				T9_ = (NIM_BOOL)0;
				T9_ = (s.len <= i);
				if (T9_) goto LA10_;
				if ((NU)(i) >= (NU)s.len) raiseIndexError2(i,s.len-1);
				if ((NU)(i) >= (NU)prefix.len) raiseIndexError2(i,prefix.len-1);
				T9_ = !(((NU8)(s.p->data[i]) == (NU8)(prefix.p->data[i])));
				LA10_: ;
				if (!T9_) goto LA11_;
				result = NIM_FALSE;
				goto BeforeRet_;
			}
			LA11_: ;
			nimln_(1541, "/p/Nim/lib/pure/strutils.nim");
			TM__JGc9b9bh2D3nTdUR7TGyq8aA_2 = addInt(i, ((NI) 1));
			i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2);
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		if (!(s.len == ((NI) 0))) goto LA3_;
		result = "";
	}
	goto LA1_;
	LA3_: ;
	{
		result = ((NCSTRING) ((*s.p).data));
	}
	LA1_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s, NIM_CHAR sub, NI start, NI last) {
	NI result;
	NI last_2;
	NI L;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_3;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_4;
	nimfr_("find", "/p/Nim/lib/pure/strutils.nim");
{	result = (NI)0;
	nimln_(1862, "/p/Nim/lib/pure/strutils.nim");
	{
		if (!(last == ((NI) 0))) goto LA3_;
		last_2 = (s.len-1);
	}
	goto LA1_;
	LA3_: ;
	{
		last_2 = last;
	}
	LA1_: ;
	nimln_(1868, "/p/Nim/lib/pure/strutils.nim");
	TM__JGc9b9bh2D3nTdUR7TGyq8aA_3 = subInt(last_2, ((NI) (start)));
	TM__JGc9b9bh2D3nTdUR7TGyq8aA_4 = addInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_3), ((NI) 1));
	L = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4);
	nimln_(1869, "/p/Nim/lib/pure/strutils.nim");
	{
		void* found;
		if (!(((NI) 0) < L)) goto LA8_;
		nimln_(1870, "/p/Nim/lib/pure/strutils.nim");
		if ((NU)(start) >= (NU)s.len) raiseIndexError2(start,s.len-1);
		found = memchr(((void*) ((&s.p->data[start]))), sub, L);
		nimln_(1871, "/p/Nim/lib/pure/strutils.nim");
		{
			if (!!((found == 0))) goto LA12_;
			nimln_(1872, "/p/Nim/lib/pure/strutils.nim");
			result = (NI)((NU64)(((NI) (ptrdiff_t) (found))) - (NU64)(((NI) (nimToCStringConv(s)))));
			goto BeforeRet_;
		}
		LA12_: ;
	}
	LA8_: ;
	nimln_(1876, "/p/Nim/lib/pure/strutils.nim");
	result = ((NI) -1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
