/* Generated by Nim Compiler v0.20.99 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g;
typedef struct NimStrPayload NimStrPayload;
typedef struct AllocatorObj AllocatorObj;
typedef struct NimStringV2 NimStringV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct NimStrPayload {
NI cap;
AllocatorObj* allocator;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct TNimType {
void* destructor;
NI size;
NCSTRING name;
};
struct RootObj {
TNimType* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
NU raiseId;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc__NT9bSe2DDkjdtx7j9aov2Z6g;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc__NT9bSe2DDkjdtx7j9aov2Z6g raiseAction;
};
typedef NI32 tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg;
struct tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g {
  Exception Sup;
tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg code;
};
typedef tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg tyArray__r9a1vSrQqNjC4iSkeSCZBVw[9];
typedef N_NIMCALL_PTR(void*, tyProc__g4DU8Xso7TeLfKjjMA54hg) (AllocatorObj* a, NI size, NI alignment);
typedef N_NIMCALL_PTR(void, tyProc__f0fmYWZ9bBl5n2coKW0dYBQ) (AllocatorObj* a, void* p, NI size);
typedef N_NIMCALL_PTR(void*, tyProc__pc9bof8Viqlm9byLAeLaBy4g) (AllocatorObj* a, void* p, NI oldSize, NI newSize);
typedef N_NIMCALL_PTR(void, tyProc__up7108S0Kt9cUg781lCWRSQ) (AllocatorObj* a);
typedef NU8 tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg;
struct AllocatorObj {
TNimType* m_type;
tyProc__g4DU8Xso7TeLfKjjMA54hg alloc;
tyProc__f0fmYWZ9bBl5n2coKW0dYBQ dealloc;
tyProc__pc9bof8Viqlm9byLAeLaBy4g realloc;
tyProc__up7108S0Kt9cUg781lCWRSQ deallocAll;
tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg flags;
NCSTRING name;
NI allocCount;
NI deallocCount;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap;AllocatorObj* allocator;tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      N_STDCALL(void, glClearColor)(NF32 red, NF32 green, NF32 blue, NF32 alpha);
N_LIB_PRIVATE N_NIMCALL(void, checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw)(void);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg, getGLerrorCode__7adr7YxxCDnx5qZN9b2oelQ)(void);
N_STDCALL(NU32, glGetError)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, popSafePoint)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vNMHbOWB6TQUp9cFTe8m56g)(tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___RPvUNk38utrLtjtQqK9cB3Q)(tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g** dest, tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g*, new__YgQmK9b6iECf2h9bYwxAeb5w)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ahHhkLNuL7qry63Yu1XXeg)(tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g* dest);
N_NIMCALL(void, nimDecWeakRef)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___4fQQqvAqifkWGVa4g39cI5A)(tySequence__uB9b75OUPRENsBAu4AnoePA* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___DIcC9aWE9a1j4i8b8InW89b1A)(tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg e);
N_LIB_PRIVATE N_NIMCALL(void, eq___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src);
N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, eq___RPvUNk38utrLtjtQqK9cB3Q_2)(tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g** dest, tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g* src);
N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
static N_INLINE(TFrame*, getFrame)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
N_STDCALL(void, glClear)(NU32 mask);
N_STDCALL(NU32, glCreateShader)(NU32 type_0);
N_STDCALL(void, glShaderSource)(NU32 shader, NI32 count, NCSTRING* string, NI32* length);
N_STDCALL(void, glCompileShader)(NU32 shader);
N_STDCALL(void, glGetShaderiv)(NU32 shader, NU32 pname, NI32* params);
N_STDCALL(void, glGetShaderInfoLog)(NU32 shader, NI32 bufSize, NI32* length, NCSTRING infoLog);
N_STDCALL(void, glDeleteShader)(NU32 shader);
N_STDCALL(NU32, glCreateProgram)(void);
N_STDCALL(void, glAttachShader)(NU32 program, NU32 shader);
N_STDCALL(void, glBindAttribLocation)(NU32 program, NU32 index, NCSTRING name);
N_STDCALL(void, glLinkProgram)(NU32 program);
N_STDCALL(void, glUseProgram)(NU32 program);
N_STDCALL(void, glGenBuffers)(NI32 n, NU32* buffers);
N_STDCALL(void, glBindBuffer)(NU32 target, NU32 buffer);
N_STDCALL(void, glEnableVertexAttribArray)(NU32 index);
N_STDCALL(void, glVertexAttribPointer)(NU32 index, NI32 size, NU32 type_0, NIM_BOOL normalized, NI32 stride, void* pointer);
N_STDCALL(void, glBufferData)(NU32 target, NI size, void* data, NU32 usage);
N_STDCALL(void, glDrawArrays)(NU32 mode, NI32 first, NI32 count);
N_STDCALL(void, glViewport)(NI32 x, NI32 y, NI32 width, NI32 height);
NIM_BOOL gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
NIM_BOOL gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg;
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
TNimType NTI__wF8RIFtaMM1xhc9cykFAs8g_;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
NIM_CONST tyArray__r9a1vSrQqNjC4iSkeSCZBVw AllErrorCodes__uuQ5exRDU8GgDnqBcqZ3Cw = {((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 0),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1280),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1281),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1282),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1283),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1284),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1285),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1286),
((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 32817)}
;
static const struct {
  NI cap; void* allocator; NIM_CHAR data[14+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_3 = { 14, NIM_NIL, "OpenGL error: " };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_4 = {14, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_3};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[8+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_7 = { 8, NIM_NIL, "no error" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_8 = {8, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_7};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[12+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_9 = { 12, NIM_NIL, "invalid enum" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_10 = {12, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_9};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[13+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_11 = { 13, NIM_NIL, "invalid value" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_12 = {13, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_11};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[17+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_13 = { 17, NIM_NIL, "invalid operation" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_14 = {17, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_13};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[14+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_15 = { 14, NIM_NIL, "stack overflow" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_16 = {14, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_15};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[15+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_17 = { 15, NIM_NIL, "stack underflow" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_18 = {15, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_17};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[13+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_19 = { 13, NIM_NIL, "out of memory" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_20 = {13, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_19};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[29+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_21 = { 29, NIM_NIL, "invalid framebuffer operation" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_22 = {29, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_21};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[15+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_23 = { 15, NIM_NIL, "table too large" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_24 = {15, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_23};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[23+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_26 = { 23, NIM_NIL, "OpenGL error: unknown (" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_27 = {23, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_26};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[1+1];
} TM__5OHv4B5juaNW3eJpx9bSMRg_28 = { 1, NIM_NIL, ")" };
static const NimStringV2 TM__5OHv4B5juaNW3eJpx9bSMRg_29 = {1, (NimStrPayload*)&TM__5OHv4B5juaNW3eJpx9bSMRg_28};

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler__rqLlY5bs9atDw2OXYqJEn5g;
	excHandler__rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA9_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg, getGLerrorCode__7adr7YxxCDnx5qZN9b2oelQ)(void) {
	tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg result;
	NU32 T1_;
	nimfr_("getGLerrorCode", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	result = (tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg)0;
	nimln_(77, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	T1_ = (NU32)0;
	T1_ = glGetError();
	result = ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg)chckRange(T1_, ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 0), ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 32817)));
	popFrame();
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler__rqLlY5bs9atDw2OXYqJEn5g = (*excHandler__rqLlY5bs9atDw2OXYqJEn5g).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ahHhkLNuL7qry63Yu1XXeg)(tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g* dest) {
	{
		if (!(*dest).Sup.up) goto LA3_;
		nimDecWeakRef((*dest).Sup.up);
	}
	LA3_: ;
	{
		if (!(*dest).Sup.parent) goto LA7_;
		nimDecWeakRef((*dest).Sup.parent);
	}
	LA7_: ;
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).Sup.message));
	eqdestroy___4fQQqvAqifkWGVa4g39cI5A((&(*dest).Sup.trace));
}

static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {
	{
		NI TM__5OHv4B5juaNW3eJpx9bSMRg_5;
		NI TM__5OHv4B5juaNW3eJpx9bSMRg_6;
		if (!(((NI) 0) < src.len)) goto LA3_;
		TM__5OHv4B5juaNW3eJpx9bSMRg_5 = addInt(src.len, ((NI) 1));
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI)chckRange((NI)(TM__5OHv4B5juaNW3eJpx9bSMRg_5), ((NI) 0), ((NI) 2147483647))));
		TM__5OHv4B5juaNW3eJpx9bSMRg_6 = addInt((*dest).len, src.len);
		(*dest).len = (NI)(TM__5OHv4B5juaNW3eJpx9bSMRg_6);
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___DIcC9aWE9a1j4i8b8InW89b1A)(tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg e) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	switch (e) {
	case ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 0):
	{
		eq___aBBXmHFBEivKqERloP6zmA_2((&result), TM__5OHv4B5juaNW3eJpx9bSMRg_8);
	}
	break;
	case ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1280):
	{
		eq___aBBXmHFBEivKqERloP6zmA_2((&result), TM__5OHv4B5juaNW3eJpx9bSMRg_10);
	}
	break;
	case ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1281):
	{
		eq___aBBXmHFBEivKqERloP6zmA_2((&result), TM__5OHv4B5juaNW3eJpx9bSMRg_12);
	}
	break;
	case ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1282):
	{
		eq___aBBXmHFBEivKqERloP6zmA_2((&result), TM__5OHv4B5juaNW3eJpx9bSMRg_14);
	}
	break;
	case ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1283):
	{
		eq___aBBXmHFBEivKqERloP6zmA_2((&result), TM__5OHv4B5juaNW3eJpx9bSMRg_16);
	}
	break;
	case ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1284):
	{
		eq___aBBXmHFBEivKqERloP6zmA_2((&result), TM__5OHv4B5juaNW3eJpx9bSMRg_18);
	}
	break;
	case ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1285):
	{
		eq___aBBXmHFBEivKqERloP6zmA_2((&result), TM__5OHv4B5juaNW3eJpx9bSMRg_20);
	}
	break;
	case ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 1286):
	{
		eq___aBBXmHFBEivKqERloP6zmA_2((&result), TM__5OHv4B5juaNW3eJpx9bSMRg_22);
	}
	break;
	case ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 32817):
	{
		eq___aBBXmHFBEivKqERloP6zmA_2((&result), TM__5OHv4B5juaNW3eJpx9bSMRg_24);
	}
	break;
	}
	return result;
}

static N_INLINE(TFrame*, getFrame)(void) {
	TFrame* result;
	result = (TFrame*)0;
	result = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	return result;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

N_LIB_PRIVATE N_NIMCALL(void, checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw)(void) {
	tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g* exc;
	NimStringV2 colontmpD_;
	tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g* colontmpD__2;
	NimStringV2 colontmpD__3;
	tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g* colontmpD__4;
	TSafePoint TM__5OHv4B5juaNW3eJpx9bSMRg_2;
	TFrame* _nimCurFrame;
	nimfr_("checkGLerror", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
{	_nimCurFrame = getFrame();
	exc = (tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g*)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = (tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g*)0;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD__4 = (tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g*)0;
	nimln_(87, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	pushSafePoint(&TM__5OHv4B5juaNW3eJpx9bSMRg_2);
	TM__5OHv4B5juaNW3eJpx9bSMRg_2.status = setjmp(TM__5OHv4B5juaNW3eJpx9bSMRg_2.context);
	if (TM__5OHv4B5juaNW3eJpx9bSMRg_2.status == 0) {
		tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg error;
		tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g* T6_;
		NimStringV2 T24_;
		NimStringV2 T25_;
		nimln_(90, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		error = getGLerrorCode__7adr7YxxCDnx5qZN9b2oelQ();
		nimln_(91, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		{
			if (!(error == ((tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg) 0))) goto LA4_;
			nimln_(92, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
			popSafePoint();
			nimln_(34, "/p/Nim/lib/system/fatal.nim");
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__3));
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
			nimln_(1724, "/p/Nim/lib/system.nim");
			eqdestroy___vNMHbOWB6TQUp9cFTe8m56g(&exc);
			goto BeforeRet_;
		}
		LA4_: ;
		nimln_(95, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		T6_ = (tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g*)0;
		T6_ = new__YgQmK9b6iECf2h9bYwxAeb5w();
		nimln_(1724, "/p/Nim/lib/system.nim");
		eqsink___RPvUNk38utrLtjtQqK9cB3Q(&exc, T6_);
		{
			tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg e;
			NI i;
			e = (tyEnum_GLerrorCode__ovQg9aLuoEQKuJYv9aVXA3Jg)0;
			nimln_(17, "/p/Nim/lib/system/iterators.nim");
			i = ((NI) 0);
			nimln_(18, "/p/Nim/lib/system/iterators.nim");
			{
				if (!(((NI) (i)) <= ((NI) 8))) goto LA10_;
				{
					nimln_(19, "/p/Nim/lib/system/iterators.nim");
					while (1) {
						NI TM__5OHv4B5juaNW3eJpx9bSMRg_25;
						nimln_(96, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
						e = AllErrorCodes__uuQ5exRDU8GgDnqBcqZ3Cw[(i)- 0];
						nimln_(97, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
						{
							NimStringV2 T18_;
							NimStringV2 T19_;
							if (!(e == error)) goto LA16_;
							nimln_(34, "/p/Nim/lib/system/fatal.nim");
							nimln_(98, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
							T18_.len = 0; T18_.p = NIM_NIL;
							nimln_(34, "/p/Nim/lib/system/fatal.nim");
							nimln_(98, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
							T19_.len = 0; T19_.p = NIM_NIL;
							T19_ = dollar___DIcC9aWE9a1j4i8b8InW89b1A(e);
							nimln_(34, "/p/Nim/lib/system/fatal.nim");
							eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T19_);
							T18_ = rawNewString(colontmpD_.len + 14);
appendString((&T18_), TM__5OHv4B5juaNW3eJpx9bSMRg_4);
appendString((&T18_), colontmpD_);
							eqsink___aBBXmHFBEivKqERloP6zmA((&(*exc).Sup.message), T18_);
							nimln_(99, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
							colontmpD__2 = 0;
							nimln_(1724, "/p/Nim/lib/system.nim");
							eq___RPvUNk38utrLtjtQqK9cB3Q_2(&colontmpD__2, exc);
							nimln_(99, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
							exc = 0;
							raiseExceptionEx((Exception*)colontmpD__2, "GLerror", "checkGLerror", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim", 99);
							colontmpD__2 = NIM_NIL;
						}
						LA16_: ;
						nimln_(21, "/p/Nim/lib/system/iterators.nim");
						{
							if (!(((NI) 8) <= ((NI) (i)))) goto LA22_;
							goto LA12;
						}
						LA22_: ;
						nimln_(22, "/p/Nim/lib/system/iterators.nim");
						TM__5OHv4B5juaNW3eJpx9bSMRg_25 = addInt(i, ((NI) 1));
						if (TM__5OHv4B5juaNW3eJpx9bSMRg_25 < 0 || TM__5OHv4B5juaNW3eJpx9bSMRg_25 > 8) raiseOverflow();
						i = (NI)(TM__5OHv4B5juaNW3eJpx9bSMRg_25);
					}
				} LA12: ;
			}
			LA10_: ;
		}
		nimln_(101, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		(*exc).code = error;
		nimln_(34, "/p/Nim/lib/system/fatal.nim");
		nimln_(102, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		T24_.len = 0; T24_.p = NIM_NIL;
		nimln_(34, "/p/Nim/lib/system/fatal.nim");
		nimln_(102, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		T25_.len = 0; T25_.p = NIM_NIL;
		T25_ = dollar___DIcC9aWE9a1j4i8b8InW89b1A(error);
		nimln_(34, "/p/Nim/lib/system/fatal.nim");
		eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__3), T25_);
		T24_ = rawNewString(colontmpD__3.len + 24);
appendString((&T24_), TM__5OHv4B5juaNW3eJpx9bSMRg_27);
appendString((&T24_), colontmpD__3);
appendString((&T24_), TM__5OHv4B5juaNW3eJpx9bSMRg_29);
		eqsink___aBBXmHFBEivKqERloP6zmA((&(*exc).Sup.message), T24_);
		nimln_(103, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		colontmpD__4 = 0;
		nimln_(1724, "/p/Nim/lib/system.nim");
		eq___RPvUNk38utrLtjtQqK9cB3Q_2(&colontmpD__4, exc);
		nimln_(103, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		exc = 0;
		raiseExceptionEx((Exception*)colontmpD__4, "GLerror", "checkGLerror", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim", 103);
		colontmpD__4 = NIM_NIL;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame(_nimCurFrame);
	}
	{
		nimln_(34, "/p/Nim/lib/system/fatal.nim");
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__3));
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
		nimln_(1724, "/p/Nim/lib/system.nim");
		eqdestroy___vNMHbOWB6TQUp9cFTe8m56g(&exc);
	}
	if (TM__5OHv4B5juaNW3eJpx9bSMRg_2.status != 0) reraiseException();
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glClearColor__mRmvKpMRWVe0olxA2D6ibg)(NF32 red, NF32 green, NF32 blue, NF32 alpha) {
	nimfr_("glClearColor", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glClearColor(red, green, blue, alpha);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glClear__bP2CTzt9boHsiXofCPEwKlw)(NU32 mask) {
	nimfr_("glClear", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glClear(mask);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(NU32, glCreateShader__aJRhkMsONGw6YriVczeVXw)(NU32 type_0) {
	NU32 result;
	nimfr_("glCreateShader", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	result = (NU32)0;
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	result = glCreateShader(type_0);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_STDCALL(void, glShaderSource__aAChP39b9c74do2PBxq3lQ2w)(NU32 shader, NI32 count, NCSTRING* string, NI32* length) {
	nimfr_("glShaderSource", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glShaderSource(shader, count, string, length);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glCompileShader__JXarxWIUYZC38YQw9bzOQOQ)(NU32 shader) {
	nimfr_("glCompileShader", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glCompileShader(shader);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glGetShaderiv__7nfLUNau354MWYxYlFPRkQ)(NU32 shader, NU32 pname, NI32* params) {
	nimfr_("glGetShaderiv", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glGetShaderiv(shader, pname, params);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glGetShaderInfoLog__P49ccOMvJ0UTL619cwd54DAw)(NU32 shader, NI32 bufSize, NI32* length, NCSTRING infoLog) {
	nimfr_("glGetShaderInfoLog", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glGetShaderInfoLog(shader, bufSize, length, infoLog);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glDeleteShader__JXarxWIUYZC38YQw9bzOQOQ_2)(NU32 shader) {
	nimfr_("glDeleteShader", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glDeleteShader(shader);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(NU32, glCreateProgram__5U6O7XOWiz3Kro2j6K7fHg)(void) {
	NU32 result;
	nimfr_("glCreateProgram", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	result = (NU32)0;
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	result = glCreateProgram();
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_STDCALL(void, glAttachShader__59cx9cQog6uHwSy9cvdhQccbw)(NU32 program, NU32 shader) {
	nimfr_("glAttachShader", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glAttachShader(program, shader);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glBindAttribLocation__uRnkKx7xCCCMIm9bGBTjK9bw)(NU32 program, NU32 index, NCSTRING name) {
	nimfr_("glBindAttribLocation", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glBindAttribLocation(program, index, name);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glLinkProgram__VmBV9c0dEsSOFA4kB5FAiVw)(NU32 program) {
	nimfr_("glLinkProgram", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glLinkProgram(program);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glUseProgram__VmBV9c0dEsSOFA4kB5FAiVw_2)(NU32 program) {
	nimfr_("glUseProgram", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glUseProgram(program);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glGenBuffers__aY0U7QWUPiGqN6yoXyh0iw)(NI32 n, NU32* buffers) {
	nimfr_("glGenBuffers", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glGenBuffers(n, buffers);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glBindBuffer__WUKuVaNXamgrBpVZ9bAUV9cA)(NU32 target, NU32 buffer) {
	nimfr_("glBindBuffer", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glBindBuffer(target, buffer);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glEnableVertexAttribArray__L4zGXkv7mX9cYBOWvb4Jlrg)(NU32 index) {
	nimfr_("glEnableVertexAttribArray", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glEnableVertexAttribArray(index);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glVertexAttribPointer__vD9cW9bmh7DJKgusHwHNi9byw)(NU32 index, NI32 size, NU32 type_0, NIM_BOOL normalized, NI32 stride, void* pointer) {
	nimfr_("glVertexAttribPointer", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glVertexAttribPointer(index, size, type_0, normalized, stride, pointer);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glBufferData__VLz8e7mQdBq50nh4P9btjaA)(NU32 target, NI size, void* data, NU32 usage) {
	nimfr_("glBufferData", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glBufferData(target, size, data, usage);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glDrawArrays__4aN8a5dpLSl7We9cWglkQeA)(NU32 mode, NI32 first, NI32 count) {
	nimfr_("glDrawArrays", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glDrawArrays(mode, first, count);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glViewport__d738gxwcyV6Jhkv9aL2fVlQ)(NI32 x, NI32 y, NI32 width, NI32 height) {
	nimfr_("glViewport", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	glViewport(x, y, width, height);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
		checkGLerror__iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, opengl_openglInit000)(void) {
{
	nimfr_("opengl", "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl.nim");
	nimln_(117, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	gAutoGLerrorCheck__8T8mi9a9bySKVpbya9cdueyBw = NIM_TRUE;
	nimln_(118, "/Users/andre.vonhouck/.nimble/pkgs/opengl-#head/opengl/private/"
"errors.nim");
	gInsideBeginEnd__A6d9af29c8SzFvWZSgv9aykVg = NIM_FALSE;
	popFrame();
}
}

N_LIB_PRIVATE N_NIMCALL(void, opengl_openglDatInit000)(void) {
NTI__wF8RIFtaMM1xhc9cykFAs8g_.destructor = (void*)eqdestroy___ahHhkLNuL7qry63Yu1XXeg; NTI__wF8RIFtaMM1xhc9cykFAs8g_.size = sizeof(tyObject_GLerror__wF8RIFtaMM1xhc9cykFAs8g); NTI__wF8RIFtaMM1xhc9cykFAs8g_.name = "|opengl.opengl.GLerror|opengl.opengl.Exception|opengl.opengl.Ro"
"otObj|";
}

