/* Generated by Nim Compiler v0.20.99 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct tyObject_GLerror_wF8RIFtaMM1xhc9cykFAs8g tyObject_GLerror_wF8RIFtaMM1xhc9cykFAs8g;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef NI32 tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
NCSTRING name;
TNimType* nextType;
NI instances;
NI sizes;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
NU raiseId;
Exception* up;
};
struct tyObject_GLerror_wF8RIFtaMM1xhc9cykFAs8g {
  Exception Sup;
tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg code;
};
typedef tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg tyArray_r9a1vSrQqNjC4iSkeSCZBVw[9];
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
NI allocCounter;
NI deallocCounter;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_STDCALL(void, glClearColor)(NF32 red, NF32 green, NF32 blue, NF32 alpha);
N_LIB_PRIVATE N_NIMCALL(void, checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw)(void);
N_LIB_PRIVATE N_NIMCALL(tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg, getGLerrorCode_7adr7YxxCDnx5qZN9b2oelQ)(void);
N_STDCALL(NU32, glGetError)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached_mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_GLerror_wF8RIFtaMM1xhc9cykFAs8g*, new_YgQmK9b6iECf2h9bYwxAeb5w)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_1f3aVIhboUJS2OaJ0h5DXA)(void* p, NI op);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr);
static N_INLINE(void, decRef_AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_Y66tOYFjgwJ0k4aLz4bc0Q)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_STDCALL(void, glClear)(NU32 mask);
N_STDCALL(NU32, glCreateShader)(NU32 type_0);
N_STDCALL(void, glShaderSource)(NU32 shader, NI32 count, NCSTRING* string, NI32* length);
N_STDCALL(void, glCompileShader)(NU32 shader);
N_STDCALL(void, glGetShaderiv)(NU32 shader, NU32 pname, NI32* params);
N_STDCALL(void, glGetShaderInfoLog)(NU32 shader, NI32 bufSize, NI32* length, NCSTRING infoLog);
N_STDCALL(void, glDeleteShader)(NU32 shader);
N_STDCALL(NU32, glCreateProgram)(void);
N_STDCALL(void, glAttachShader)(NU32 program, NU32 shader);
N_STDCALL(void, glBindAttribLocation)(NU32 program, NU32 index, NCSTRING name);
N_STDCALL(void, glLinkProgram)(NU32 program);
N_STDCALL(void, glUseProgram)(NU32 program);
N_STDCALL(void, glGenBuffers)(NI32 n, NU32* buffers);
N_STDCALL(void, glBindBuffer)(NU32 target, NU32 buffer);
N_STDCALL(void, glEnableVertexAttribArray)(NU32 index);
N_STDCALL(void, glVertexAttribPointer)(NU32 index, NI32 size, NU32 type_0, NIM_BOOL normalized, NI32 stride, void* pointer);
N_STDCALL(void, glBufferData)(NU32 target, NI size, void* data, NU32 usage);
N_STDCALL(void, glDrawArrays)(NU32 mode, NI32 first, NI32 count);
N_STDCALL(void, glViewport)(NI32 x, NI32 y, NI32 width, NI32 height);
NIM_BOOL gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
NIM_BOOL gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_XEycrCsme5C8CVWAYEcdBQ_;
extern TNimType* nimTypeRoot;
TNimType NTI_wF8RIFtaMM1xhc9cykFAs8g_;
TNimType NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_;
TNimType NTI_1f3aVIhboUJS2OaJ0h5DXA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NIM_CONST tyArray_r9a1vSrQqNjC4iSkeSCZBVw AllErrorCodes_uuQ5exRDU8GgDnqBcqZ3Cw = {((tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg) 0),
((tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg) 1280),
((tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg) 1281),
((tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg) 1282),
((tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg) 1283),
((tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg) 1284),
((tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg) 1285),
((tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg) 1286),
((tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg) 32817)}
;
STRING_LITERAL(TM_5OHv4B5juaNW3eJpx9bSMRg_5, "OpenGL error: ", 14);
STRING_LITERAL(TM_5OHv4B5juaNW3eJpx9bSMRg_7, "OpenGL error: unknown (", 23);
STRING_LITERAL(TM_5OHv4B5juaNW3eJpx9bSMRg_8, ")", 1);

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA9_;
		callDepthLimitReached_mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg, getGLerrorCode_7adr7YxxCDnx5qZN9b2oelQ)(void) {
	tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg result;
	NU32 T1_;
	nimfr_("getGLerrorCode", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	result = (tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg)0;
	nimln_(77, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	T1_ = (NU32)0;
	T1_ = glGetError();
	result = ((tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg)chckRange(T1_, ((tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg) 0), ((tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg) 32817)));
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_1f3aVIhboUJS2OaJ0h5DXA)(void* p, NI op) {
	tyObject_GLerror_wF8RIFtaMM1xhc9cykFAs8g* a;
	a = (tyObject_GLerror_wF8RIFtaMM1xhc9cykFAs8g*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.up, op);
}

static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, copyMem_M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == NIM_NIL))) goto LA3_;
		copyMem_M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}

static N_INLINE(void, incRef_AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/gc.nim");
	nimln_(183, "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/gc.nim");
	(*c).refcount = (NI)((NU32)((*c).refcount) + (NU32)(((NI) 8)));
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(129, "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU32)(((NI) (ptrdiff_t) (usr))) - (NU32)(((NI) 8)))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/gc.nim");
	nimln_(195, "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/gc.nim");
	addZCT_Y66tOYFjgwJ0k4aLz4bc0Q((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/gc.nim");
	nimln_(200, "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/gc.nim");
	(*c).refcount = (NI)((NU32)((*c).refcount) - (NU32)(((NI) 8)));
	nimln_(201, "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/gc.nim");
	{
		if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA3_;
		nimln_(202, "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/gc.nim");
		rtlAddZCT_AT1eRuflKWyTTBdLjEDZbg_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/gc.nim");
	nimln_(238, "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_QFQqcLB3lgOdwipkv9a60xwsystem(src);
		incRef_AT1eRuflKWyTTBdLjEDZbg_3system(T5_);
	}
	LA3_: ;
	nimln_(239, "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_QFQqcLB3lgOdwipkv9a60xwsystem((*dest));
		decRef_AT1eRuflKWyTTBdLjEDZbgsystem(T10_);
	}
	LA8_: ;
	nimln_(240, "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw)(void) {
	tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg error;
	tyObject_GLerror_wF8RIFtaMM1xhc9cykFAs8g* exc;
	NimStringDesc* T21_;
	nimfr_("checkGLerror", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
{	nimln_(90, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	error = getGLerrorCode_7adr7YxxCDnx5qZN9b2oelQ();
	nimln_(91, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		if (!(error == ((tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg) 0))) goto LA3_;
		nimln_(92, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(95, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	exc = new_YgQmK9b6iECf2h9bYwxAeb5w();
	{
		tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg e;
		NI i;
		e = (tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg)0;
		nimln_(17, "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/iterators.nim");
		i = ((NI) 0);
		nimln_(18, "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/iterators.nim");
		{
			if (!(((NI) (i)) <= ((NI) 8))) goto LA8_;
			{
				nimln_(19, "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/iterators.nim");
				while (1) {
					NI TM_5OHv4B5juaNW3eJpx9bSMRg_6;
					nimln_(96, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
					e = AllErrorCodes_uuQ5exRDU8GgDnqBcqZ3Cw[(i)- 0];
					nimln_(97, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
					{
						NimStringDesc* T16_;
						if (!(e == error)) goto LA14_;
						nimln_(98, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
						T16_ = (NimStringDesc*)0;
						T16_ = rawNewString((reprEnum((NI)e, (&NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_)) ? reprEnum((NI)e, (&NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_))->Sup.len : 0) + 14);
appendString(T16_, ((NimStringDesc*) &TM_5OHv4B5juaNW3eJpx9bSMRg_5));
appendString(T16_, reprEnum((NI)e, (&NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_)));
						asgnRef((void**) (&(*exc).Sup.message), T16_);
						nimln_(99, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
						raiseExceptionEx((Exception*)exc, "GLerror", "checkGLerror", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim", 99);
					}
					LA14_: ;
					nimln_(21, "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/iterators.nim");
					{
						if (!(((NI) 8) <= ((NI) (i)))) goto LA19_;
						goto LA10;
					}
					LA19_: ;
					nimln_(22, "/Users/andre.vonhouck/.choosenim/toolchains/nim-#devel/lib/syst"
"em/iterators.nim");
					TM_5OHv4B5juaNW3eJpx9bSMRg_6 = addInt(i, ((NI) 1));
					if (TM_5OHv4B5juaNW3eJpx9bSMRg_6 < 0 || TM_5OHv4B5juaNW3eJpx9bSMRg_6 > 8) raiseOverflow();
					i = (NI)(TM_5OHv4B5juaNW3eJpx9bSMRg_6);
				}
			} LA10: ;
		}
		LA8_: ;
	}
	nimln_(101, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	(*exc).code = error;
	nimln_(102, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	T21_ = (NimStringDesc*)0;
	T21_ = rawNewString((reprEnum((NI)error, (&NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_)) ? reprEnum((NI)error, (&NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_))->Sup.len : 0) + 24);
appendString(T21_, ((NimStringDesc*) &TM_5OHv4B5juaNW3eJpx9bSMRg_7));
appendString(T21_, reprEnum((NI)error, (&NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_)));
appendString(T21_, ((NimStringDesc*) &TM_5OHv4B5juaNW3eJpx9bSMRg_8));
	asgnRef((void**) (&(*exc).Sup.message), T21_);
	nimln_(103, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	raiseExceptionEx((Exception*)exc, "GLerror", "checkGLerror", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim", 103);
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glClearColor_mRmvKpMRWVe0olxA2D6ibg)(NF32 red, NF32 green, NF32 blue, NF32 alpha) {
	nimfr_("glClearColor", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glClearColor(red, green, blue, alpha);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glClear_bP2CTzt9boHsiXofCPEwKlw)(NU32 mask) {
	nimfr_("glClear", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glClear(mask);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(NU32, glCreateShader_aJRhkMsONGw6YriVczeVXw)(NU32 type_0) {
	NU32 result;
	nimfr_("glCreateShader", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	result = (NU32)0;
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	result = glCreateShader(type_0);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_STDCALL(void, glShaderSource_aAChP39b9c74do2PBxq3lQ2w)(NU32 shader, NI32 count, NCSTRING* string, NI32* length) {
	nimfr_("glShaderSource", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glShaderSource(shader, count, string, length);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glCompileShader_JXarxWIUYZC38YQw9bzOQOQ)(NU32 shader) {
	nimfr_("glCompileShader", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glCompileShader(shader);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glGetShaderiv_7nfLUNau354MWYxYlFPRkQ)(NU32 shader, NU32 pname, NI32* params) {
	nimfr_("glGetShaderiv", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glGetShaderiv(shader, pname, params);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glGetShaderInfoLog_P49ccOMvJ0UTL619cwd54DAw)(NU32 shader, NI32 bufSize, NI32* length, NCSTRING infoLog) {
	nimfr_("glGetShaderInfoLog", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glGetShaderInfoLog(shader, bufSize, length, infoLog);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glDeleteShader_JXarxWIUYZC38YQw9bzOQOQ_2)(NU32 shader) {
	nimfr_("glDeleteShader", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glDeleteShader(shader);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(NU32, glCreateProgram_5U6O7XOWiz3Kro2j6K7fHg)(void) {
	NU32 result;
	nimfr_("glCreateProgram", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	result = (NU32)0;
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	result = glCreateProgram();
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_STDCALL(void, glAttachShader_59cx9cQog6uHwSy9cvdhQccbw)(NU32 program, NU32 shader) {
	nimfr_("glAttachShader", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glAttachShader(program, shader);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glBindAttribLocation_uRnkKx7xCCCMIm9bGBTjK9bw)(NU32 program, NU32 index, NCSTRING name) {
	nimfr_("glBindAttribLocation", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glBindAttribLocation(program, index, name);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glLinkProgram_VmBV9c0dEsSOFA4kB5FAiVw)(NU32 program) {
	nimfr_("glLinkProgram", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glLinkProgram(program);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glUseProgram_VmBV9c0dEsSOFA4kB5FAiVw_2)(NU32 program) {
	nimfr_("glUseProgram", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glUseProgram(program);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glGenBuffers_aY0U7QWUPiGqN6yoXyh0iw)(NI32 n, NU32* buffers) {
	nimfr_("glGenBuffers", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glGenBuffers(n, buffers);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glBindBuffer_WUKuVaNXamgrBpVZ9bAUV9cA)(NU32 target, NU32 buffer) {
	nimfr_("glBindBuffer", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glBindBuffer(target, buffer);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glEnableVertexAttribArray_L4zGXkv7mX9cYBOWvb4Jlrg)(NU32 index) {
	nimfr_("glEnableVertexAttribArray", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glEnableVertexAttribArray(index);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glVertexAttribPointer_vD9cW9bmh7DJKgusHwHNi9byw)(NU32 index, NI32 size, NU32 type_0, NIM_BOOL normalized, NI32 stride, void* pointer) {
	nimfr_("glVertexAttribPointer", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glVertexAttribPointer(index, size, type_0, normalized, stride, pointer);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glBufferData_VLz8e7mQdBq50nh4P9btjaA)(NU32 target, NI size, void* data, NU32 usage) {
	nimfr_("glBufferData", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glBufferData(target, size, data, usage);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glDrawArrays_4aN8a5dpLSl7We9cWglkQeA)(NU32 mode, NI32 first, NI32 count) {
	nimfr_("glDrawArrays", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glDrawArrays(mode, first, count);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_STDCALL(void, glViewport_d738gxwcyV6Jhkv9aL2fVlQ)(NI32 x, NI32 y, NI32 width, NI32 height) {
	nimfr_("glViewport", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"procs.nim");
	nimln_(22, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	glViewport(x, y, width, height);
	nimln_(43, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw;
		if (!(T3_)) goto LA4_;
		T3_ = !(gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(44, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
		checkGLerror_iTwC9bYVooLkAk0TsVN9c3tw();
	}
	LA5_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, opengl_openglInit000)(void) {
{
	nimfr_("opengl", "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl.nim");
	nimln_(117, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	gAutoGLerrorCheck_8T8mi9a9bySKVpbya9cdueyBw = NIM_TRUE;
	nimln_(118, "/Users/andre.vonhouck/.nimble/pkgs/opengl-1.2.0/opengl/private/"
"errors.nim");
	gInsideBeginEnd_A6d9af29c8SzFvWZSgv9aykVg = NIM_FALSE;
	popFrame();
}
}

N_LIB_PRIVATE N_NIMCALL(void, opengl_openglDatInit000)(void) {
static TNimNode* TM_5OHv4B5juaNW3eJpx9bSMRg_2_9[9];
NI TM_5OHv4B5juaNW3eJpx9bSMRg_4;
static char* NIM_CONST TM_5OHv4B5juaNW3eJpx9bSMRg_3[9] = {
"no error", 
"invalid enum", 
"invalid value", 
"invalid operation", 
"stack overflow", 
"stack underflow", 
"out of memory", 
"invalid framebuffer operation", 
"table too large"};
static TNimNode TM_5OHv4B5juaNW3eJpx9bSMRg_0[11];
NTI_wF8RIFtaMM1xhc9cykFAs8g_.size = sizeof(tyObject_GLerror_wF8RIFtaMM1xhc9cykFAs8g);
NTI_wF8RIFtaMM1xhc9cykFAs8g_.kind = 17;
NTI_wF8RIFtaMM1xhc9cykFAs8g_.base = (&NTI_XEycrCsme5C8CVWAYEcdBQ_);
NTI_wF8RIFtaMM1xhc9cykFAs8g_.name = "GLerror";
NTI_wF8RIFtaMM1xhc9cykFAs8g_.nextType = nimTypeRoot; nimTypeRoot=&NTI_wF8RIFtaMM1xhc9cykFAs8g_;
NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_.size = sizeof(tyEnum_GLerrorCode_ovQg9aLuoEQKuJYv9aVXA3Jg);
NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_.kind = 14;
NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_.base = 0;
NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_.flags = 3;
NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_.name = "GLerrorCode";
NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_.nextType = nimTypeRoot; nimTypeRoot=&NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_;
for (TM_5OHv4B5juaNW3eJpx9bSMRg_4 = 0; TM_5OHv4B5juaNW3eJpx9bSMRg_4 < 9; TM_5OHv4B5juaNW3eJpx9bSMRg_4++) {
TM_5OHv4B5juaNW3eJpx9bSMRg_0[TM_5OHv4B5juaNW3eJpx9bSMRg_4+1].kind = 1;
TM_5OHv4B5juaNW3eJpx9bSMRg_0[TM_5OHv4B5juaNW3eJpx9bSMRg_4+1].offset = TM_5OHv4B5juaNW3eJpx9bSMRg_4;
TM_5OHv4B5juaNW3eJpx9bSMRg_0[TM_5OHv4B5juaNW3eJpx9bSMRg_4+1].name = TM_5OHv4B5juaNW3eJpx9bSMRg_3[TM_5OHv4B5juaNW3eJpx9bSMRg_4];
TM_5OHv4B5juaNW3eJpx9bSMRg_2_9[TM_5OHv4B5juaNW3eJpx9bSMRg_4] = &TM_5OHv4B5juaNW3eJpx9bSMRg_0[TM_5OHv4B5juaNW3eJpx9bSMRg_4+1];
}
TM_5OHv4B5juaNW3eJpx9bSMRg_0[1].offset = 0;
TM_5OHv4B5juaNW3eJpx9bSMRg_0[2].offset = 1280;
TM_5OHv4B5juaNW3eJpx9bSMRg_0[3].offset = 1281;
TM_5OHv4B5juaNW3eJpx9bSMRg_0[4].offset = 1282;
TM_5OHv4B5juaNW3eJpx9bSMRg_0[5].offset = 1283;
TM_5OHv4B5juaNW3eJpx9bSMRg_0[6].offset = 1284;
TM_5OHv4B5juaNW3eJpx9bSMRg_0[7].offset = 1285;
TM_5OHv4B5juaNW3eJpx9bSMRg_0[8].offset = 1286;
TM_5OHv4B5juaNW3eJpx9bSMRg_0[9].offset = 32817;
TM_5OHv4B5juaNW3eJpx9bSMRg_0[10].len = 9; TM_5OHv4B5juaNW3eJpx9bSMRg_0[10].kind = 2; TM_5OHv4B5juaNW3eJpx9bSMRg_0[10].sons = &TM_5OHv4B5juaNW3eJpx9bSMRg_2_9[0];
NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_.node = &TM_5OHv4B5juaNW3eJpx9bSMRg_0[10];
NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_.flags = 1<<2;
TM_5OHv4B5juaNW3eJpx9bSMRg_0[0].kind = 1;
TM_5OHv4B5juaNW3eJpx9bSMRg_0[0].offset = offsetof(tyObject_GLerror_wF8RIFtaMM1xhc9cykFAs8g, code);
TM_5OHv4B5juaNW3eJpx9bSMRg_0[0].typ = (&NTI_ovQg9aLuoEQKuJYv9aVXA3Jg_);
TM_5OHv4B5juaNW3eJpx9bSMRg_0[0].name = "code";
NTI_wF8RIFtaMM1xhc9cykFAs8g_.node = &TM_5OHv4B5juaNW3eJpx9bSMRg_0[0];
NTI_1f3aVIhboUJS2OaJ0h5DXA_.size = sizeof(tyObject_GLerror_wF8RIFtaMM1xhc9cykFAs8g*);
NTI_1f3aVIhboUJS2OaJ0h5DXA_.kind = 22;
NTI_1f3aVIhboUJS2OaJ0h5DXA_.base = (&NTI_wF8RIFtaMM1xhc9cykFAs8g_);
NTI_1f3aVIhboUJS2OaJ0h5DXA_.name = "ref GLerror";
NTI_1f3aVIhboUJS2OaJ0h5DXA_.nextType = nimTypeRoot; nimTypeRoot=&NTI_1f3aVIhboUJS2OaJ0h5DXA_;
NTI_1f3aVIhboUJS2OaJ0h5DXA_.marker = Marker_tyRef_1f3aVIhboUJS2OaJ0h5DXA;
}

