/* Generated by Nim Compiler v0.20.99 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStrPayload NimStrPayload;
typedef struct AllocatorObj AllocatorObj;
typedef struct NimStringV2 NimStringV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_PathIter__tllF14xUpDWpqG9ci5sg9bMg tyObject_PathIter__tllF14xUpDWpqG9ci5sg9bMg;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct NimStrPayload {
NI cap;
AllocatorObj* allocator;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct TNimType {
void* destructor;
NI size;
NCSTRING name;
};
struct RootObj {
TNimType* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
NU raiseId;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc__NT9bSe2DDkjdtx7j9aov2Z6g;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc__NT9bSe2DDkjdtx7j9aov2Z6g raiseAction;
};
struct tyObject_PathIter__tllF14xUpDWpqG9ci5sg9bMg {
NI i;
NI prev;
NIM_BOOL notFirst;
};
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef N_NIMCALL_PTR(void*, tyProc__g4DU8Xso7TeLfKjjMA54hg) (AllocatorObj* a, NI size, NI alignment);
typedef N_NIMCALL_PTR(void, tyProc__f0fmYWZ9bBl5n2coKW0dYBQ) (AllocatorObj* a, void* p, NI size);
typedef N_NIMCALL_PTR(void*, tyProc__pc9bof8Viqlm9byLAeLaBy4g) (AllocatorObj* a, void* p, NI oldSize, NI newSize);
typedef N_NIMCALL_PTR(void, tyProc__up7108S0Kt9cUg781lCWRSQ) (AllocatorObj* a);
typedef NU8 tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg;
struct AllocatorObj {
TNimType* m_type;
tyProc__g4DU8Xso7TeLfKjjMA54hg alloc;
tyProc__f0fmYWZ9bBl5n2coKW0dYBQ dealloc;
tyProc__pc9bof8Viqlm9byLAeLaBy4g realloc;
tyProc__up7108S0Kt9cUg781lCWRSQ deallocAll;
tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg flags;
NCSTRING name;
NI allocCount;
NI deallocCount;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap;AllocatorObj* allocator;tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasNext__ecfBf9bSnUlnf5OQ0NQMxpQ)(tyObject_PathIter__tllF14xUpDWpqG9ci5sg9bMg it, NimStringV2 x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ, next__am1q4dBd9cls9au5CcmkX5oA)(tyObject_PathIter__tllF14xUpDWpqG9ci5sg9bMg* it, NimStringV2 x);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isSlash__Sl9c33djPmHfV9bnZbQf0QBw)(NimStringV2 x, tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ bounds);
N_NIMCALL(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isDotDot__Sl9c33djPmHfV9bnZbQf0QBw_2)(NimStringV2 x, tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ bounds);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
static N_INLINE(NIM_CHAR, X5BX5D___okzHJ6GE9cv0bYG3b4r5KCAsystem)(NimStringV2 s, NI i);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__2yh9cer0ymNRHlOOg8P7IuA)(NimStringV2 s, NI first, NI last);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isDot__Sl9c33djPmHfV9bnZbQf0QBw_3)(NimStringV2 x, tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ bounds);
N_LIB_PRIVATE N_NIMCALL(void, eq___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(TFrame*, getFrame)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_NIMCALL(void, reraiseException)(void);
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
static const struct {
  NI cap; void* allocator; NIM_CHAR data[1+1];
} TM__DfU0iuayCGwHDN1Exp9cbKg_19 = { 1, NIM_NIL, "." };
static const NimStringV2 TM__DfU0iuayCGwHDN1Exp9cbKg_20 = {1, (NimStrPayload*)&TM__DfU0iuayCGwHDN1Exp9cbKg_19};

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler__rqLlY5bs9atDw2OXYqJEn5g;
	excHandler__rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}

static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA9_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasNext__ecfBf9bSnUlnf5OQ0NQMxpQ)(tyObject_PathIter__tllF14xUpDWpqG9ci5sg9bMg it, NimStringV2 x) {
	NIM_BOOL result;
	nimfr_("hasNext", "/p/Nim/lib/pure/pathnorm.nim");
	result = (NIM_BOOL)0;
	nimln_(24, "/p/Nim/lib/pure/pathnorm.nim");
	result = (it.i < x.len);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ, next__am1q4dBd9cls9au5CcmkX5oA)(tyObject_PathIter__tllF14xUpDWpqG9ci5sg9bMg* it, NimStringV2 x) {
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ result;
	nimfr_("next", "/p/Nim/lib/pure/pathnorm.nim");
	nimZeroMem((void*)(&result), sizeof(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ));
	nimln_(27, "/p/Nim/lib/pure/pathnorm.nim");
	(*it).prev = (*it).i;
	nimln_(28, "/p/Nim/lib/pure/pathnorm.nim");
	{
		NIM_BOOL T3_;
		NI TM__DfU0iuayCGwHDN1Exp9cbKg_4;
		T3_ = (NIM_BOOL)0;
		T3_ = !((*it).notFirst);
		if (!(T3_)) goto LA4_;
		if ((NU)((*it).i) >= (NU)x.len) raiseIndexError2((*it).i,x.len-1);
		T3_ = (((NU8)(x.p->data[(*it).i])) == ((NU8)(47)) || ((NU8)(x.p->data[(*it).i])) == ((NU8)(47)));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(30, "/p/Nim/lib/pure/pathnorm.nim");
		TM__DfU0iuayCGwHDN1Exp9cbKg_4 = addInt((*it).i, ((NI) 1));
		(*it).i = (NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_4);
	}
	goto LA1_;
	LA5_: ;
	{
		{
			nimln_(36, "/p/Nim/lib/pure/pathnorm.nim");
			while (1) {
				NIM_BOOL T10_;
				NI TM__DfU0iuayCGwHDN1Exp9cbKg_5;
				T10_ = (NIM_BOOL)0;
				T10_ = ((*it).i < x.len);
				if (!(T10_)) goto LA11_;
				if ((NU)((*it).i) >= (NU)x.len) raiseIndexError2((*it).i,x.len-1);
				T10_ = !((((NU8)(x.p->data[(*it).i])) == ((NU8)(47)) || ((NU8)(x.p->data[(*it).i])) == ((NU8)(47))));
				LA11_: ;
				if (!T10_) goto LA9;
				TM__DfU0iuayCGwHDN1Exp9cbKg_5 = addInt((*it).i, ((NI) 1));
				(*it).i = (NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_5);
			} LA9: ;
		}
	}
	LA1_: ;
	nimln_(37, "/p/Nim/lib/pure/pathnorm.nim");
	{
		NI colontmp_;
		NI colontmp__2;
		NI TM__DfU0iuayCGwHDN1Exp9cbKg_6;
		if (!((*it).prev < (*it).i)) goto LA14_;
		nimln_(38, "/p/Nim/lib/pure/pathnorm.nim");
		colontmp_ = (*it).prev;
		TM__DfU0iuayCGwHDN1Exp9cbKg_6 = subInt((*it).i, ((NI) 1));
		colontmp__2 = (NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_6);
		result.Field0 = colontmp_;
		result.Field1 = colontmp__2;
	}
	goto LA12_;
	LA14_: ;
	{
		NIM_BOOL T17_;
		nimln_(39, "/p/Nim/lib/pure/pathnorm.nim");
		T17_ = (NIM_BOOL)0;
		T17_ = hasNext__ecfBf9bSnUlnf5OQ0NQMxpQ((*it), x);
		if (!T17_) goto LA18_;
		nimln_(40, "/p/Nim/lib/pure/pathnorm.nim");
		result = next__am1q4dBd9cls9au5CcmkX5oA(it, x);
	}
	goto LA12_;
	LA18_: ;
	LA12_: ;
	{
		nimln_(42, "/p/Nim/lib/pure/pathnorm.nim");
		while (1) {
			NIM_BOOL T22_;
			NI TM__DfU0iuayCGwHDN1Exp9cbKg_7;
			T22_ = (NIM_BOOL)0;
			T22_ = ((*it).i < x.len);
			if (!(T22_)) goto LA23_;
			if ((NU)((*it).i) >= (NU)x.len) raiseIndexError2((*it).i,x.len-1);
			T22_ = (((NU8)(x.p->data[(*it).i])) == ((NU8)(47)) || ((NU8)(x.p->data[(*it).i])) == ((NU8)(47)));
			LA23_: ;
			if (!T22_) goto LA21;
			TM__DfU0iuayCGwHDN1Exp9cbKg_7 = addInt((*it).i, ((NI) 1));
			(*it).i = (NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_7);
		} LA21: ;
	}
	nimln_(43, "/p/Nim/lib/pure/pathnorm.nim");
	(*it).notFirst = NIM_TRUE;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isSlash__Sl9c33djPmHfV9bnZbQf0QBw)(NimStringV2 x, tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ bounds) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isSlash", "/p/Nim/lib/pure/pathnorm.nim");
	result = (NIM_BOOL)0;
	nimln_(56, "/p/Nim/lib/pure/pathnorm.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = (bounds.Field1 == bounds.Field0);
	if (!(T1_)) goto LA2_;
	if ((NU)(bounds.Field0) >= (NU)x.len) raiseIndexError2(bounds.Field0,x.len-1);
	T1_ = (((NU8)(x.p->data[bounds.Field0])) == ((NU8)(47)) || ((NU8)(x.p->data[bounds.Field0])) == ((NU8)(47)));
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isDotDot__Sl9c33djPmHfV9bnZbQf0QBw_2)(NimStringV2 x, tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ bounds) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NI TM__DfU0iuayCGwHDN1Exp9cbKg_8;
	NI TM__DfU0iuayCGwHDN1Exp9cbKg_9;
	nimfr_("isDotDot", "/p/Nim/lib/pure/pathnorm.nim");
	result = (NIM_BOOL)0;
	nimln_(53, "/p/Nim/lib/pure/pathnorm.nim");
	T1_ = (NIM_BOOL)0;
	T2_ = (NIM_BOOL)0;
	TM__DfU0iuayCGwHDN1Exp9cbKg_8 = addInt(bounds.Field0, ((NI) 1));
	T2_ = (bounds.Field1 == (NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_8));
	if (!(T2_)) goto LA3_;
	if ((NU)(bounds.Field0) >= (NU)x.len) raiseIndexError2(bounds.Field0,x.len-1);
	T2_ = ((NU8)(x.p->data[bounds.Field0]) == (NU8)(46));
	LA3_: ;
	T1_ = T2_;
	if (!(T1_)) goto LA4_;
	TM__DfU0iuayCGwHDN1Exp9cbKg_9 = addInt(bounds.Field0, ((NI) 1));
	if ((NU)((NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_9)) >= (NU)x.len) raiseIndexError2((NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_9),x.len-1);
	T1_ = ((NU8)(x.p->data[(NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_9)]) == (NU8)(46));
	LA4_: ;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_CHAR, X5BX5D___okzHJ6GE9cv0bYG3b4r5KCAsystem)(NimStringV2 s, NI i) {
	NIM_CHAR result;
	NI TM__DfU0iuayCGwHDN1Exp9cbKg_15;
	nimfr_("[]", "/p/Nim/lib/system.nim");
	result = (NIM_CHAR)0;
	nimln_(4039, "/p/Nim/lib/system.nim");
	TM__DfU0iuayCGwHDN1Exp9cbKg_15 = subInt(s.len, i);
	if ((NU)((NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_15)) >= (NU)s.len) raiseIndexError2((NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_15),s.len-1);
	result = s.p->data[(NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_15)];
	popFrame();
	return result;
}

static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}

static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {
	{
		NI TM__DfU0iuayCGwHDN1Exp9cbKg_16;
		NI TM__DfU0iuayCGwHDN1Exp9cbKg_17;
		if (!(((NI) 0) < src.len)) goto LA3_;
		TM__DfU0iuayCGwHDN1Exp9cbKg_16 = addInt(src.len, ((NI) 1));
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI)chckRange((NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_16), ((NI) 0), ((NI) 2147483647))));
		TM__DfU0iuayCGwHDN1Exp9cbKg_17 = addInt((*dest).len, src.len);
		(*dest).len = (NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_17);
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isDot__Sl9c33djPmHfV9bnZbQf0QBw_3)(NimStringV2 x, tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ bounds) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isDot", "/p/Nim/lib/pure/pathnorm.nim");
	result = (NIM_BOOL)0;
	nimln_(50, "/p/Nim/lib/pure/pathnorm.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = (bounds.Field1 == bounds.Field0);
	if (!(T1_)) goto LA2_;
	if ((NU)(bounds.Field0) >= (NU)x.len) raiseIndexError2(bounds.Field0,x.len-1);
	T1_ = ((NU8)(x.p->data[bounds.Field0]) == (NU8)(46));
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler__rqLlY5bs9atDw2OXYqJEn5g = (*excHandler__rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(TFrame*, getFrame)(void) {
	TFrame* result;
	result = (TFrame*)0;
	result = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	return result;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

N_LIB_PRIVATE N_NIMCALL(void, addNormalizePath__bx9csIXjBBeHkYSkIUixO1g)(NimStringV2 x, NimStringV2* result, NI* state, NIM_CHAR dirSep) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	TSafePoint TM__DfU0iuayCGwHDN1Exp9cbKg_2;
	TFrame* _nimCurFrame;
	nimfr_("addNormalizePath", "/p/Nim/lib/pure/pathnorm.nim");
	_nimCurFrame = getFrame();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimln_(59, "/p/Nim/lib/pure/pathnorm.nim");
	pushSafePoint(&TM__DfU0iuayCGwHDN1Exp9cbKg_2);
	TM__DfU0iuayCGwHDN1Exp9cbKg_2.status = setjmp(TM__DfU0iuayCGwHDN1Exp9cbKg_2.context);
	if (TM__DfU0iuayCGwHDN1Exp9cbKg_2.status == 0) {
		tyObject_PathIter__tllF14xUpDWpqG9ci5sg9bMg it;
		nimZeroMem((void*)(&it), sizeof(tyObject_PathIter__tllF14xUpDWpqG9ci5sg9bMg));
		nimln_(64, "/p/Nim/lib/pure/pathnorm.nim");
		it.notFirst = (((NI) 0) < (NI)((NI32)((*state)) >> (NU32)(((NI) 1))));
		nimln_(65, "/p/Nim/lib/pure/pathnorm.nim");
		{
			if (!it.notFirst) goto LA4_;
			{
				nimln_(66, "/p/Nim/lib/pure/pathnorm.nim");
				while (1) {
					NIM_BOOL T8_;
					NI TM__DfU0iuayCGwHDN1Exp9cbKg_3;
					T8_ = (NIM_BOOL)0;
					T8_ = (it.i < x.len);
					if (!(T8_)) goto LA9_;
					if ((NU)(it.i) >= (NU)x.len) raiseIndexError2(it.i,x.len-1);
					T8_ = (((NU8)(x.p->data[it.i])) == ((NU8)(47)) || ((NU8)(x.p->data[it.i])) == ((NU8)(47)));
					LA9_: ;
					if (!T8_) goto LA7;
					TM__DfU0iuayCGwHDN1Exp9cbKg_3 = addInt(it.i, ((NI) 1));
					it.i = (NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_3);
				} LA7: ;
			}
		}
		LA4_: ;
		{
			nimln_(67, "/p/Nim/lib/pure/pathnorm.nim");
			while (1) {
				NIM_BOOL T12_;
				tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ b;
				T12_ = (NIM_BOOL)0;
				T12_ = hasNext__ecfBf9bSnUlnf5OQ0NQMxpQ(it, x);
				if (!T12_) goto LA11;
				nimln_(68, "/p/Nim/lib/pure/pathnorm.nim");
				b = next__am1q4dBd9cls9au5CcmkX5oA((&it), x);
				nimln_(69, "/p/Nim/lib/pure/pathnorm.nim");
				{
					NIM_BOOL T15_;
					T15_ = (NIM_BOOL)0;
					T15_ = ((NI)((NI32)((*state)) >> (NU32)(((NI) 1))) == ((NI) 0));
					if (!(T15_)) goto LA16_;
					T15_ = isSlash__Sl9c33djPmHfV9bnZbQf0QBw(x, b);
					LA16_: ;
					if (!T15_) goto LA17_;
					nimln_(70, "/p/Nim/lib/pure/pathnorm.nim");
					nimAddCharV1((&(*result)), dirSep);
					nimln_(71, "/p/Nim/lib/pure/pathnorm.nim");
					(*state) = (NI)((*state) | ((NI) 1));
				}
				goto LA13_;
				LA17_: ;
				{
					NIM_BOOL T20_;
					nimln_(72, "/p/Nim/lib/pure/pathnorm.nim");
					T20_ = (NIM_BOOL)0;
					T20_ = isDotDot__Sl9c33djPmHfV9bnZbQf0QBw_2(x, b);
					if (!T20_) goto LA21_;
					nimln_(73, "/p/Nim/lib/pure/pathnorm.nim");
					{
						NI d;
						if (!(((NI) 1) <= (NI)((NI32)((*state)) >> (NU32)(((NI) 1))))) goto LA25_;
						nimln_(74, "/p/Nim/lib/pure/pathnorm.nim");
						d = (*result).len;
						{
							nimln_(76, "/p/Nim/lib/pure/pathnorm.nim");
							while (1) {
								NIM_BOOL T29_;
								NI TM__DfU0iuayCGwHDN1Exp9cbKg_10;
								NI TM__DfU0iuayCGwHDN1Exp9cbKg_11;
								NI TM__DfU0iuayCGwHDN1Exp9cbKg_12;
								T29_ = (NIM_BOOL)0;
								TM__DfU0iuayCGwHDN1Exp9cbKg_10 = subInt(d, ((NI) 1));
								T29_ = ((NI)((*state) & ((NI) 1)) < (NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_10));
								if (!(T29_)) goto LA30_;
								TM__DfU0iuayCGwHDN1Exp9cbKg_11 = subInt(d, ((NI) 1));
								if ((NU)((NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_11)) >= (NU)(*result).len) raiseIndexError2((NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_11),(*result).len-1);
								T29_ = !((((NU8)((*result).p->data[(NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_11)])) == ((NU8)(47)) || ((NU8)((*result).p->data[(NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_11)])) == ((NU8)(47))));
								LA30_: ;
								if (!T29_) goto LA28;
								nimln_(77, "/p/Nim/lib/pure/pathnorm.nim");
								TM__DfU0iuayCGwHDN1Exp9cbKg_12 = subInt(d, ((NI) 1));
								d = (NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_12);
							} LA28: ;
						}
						nimln_(78, "/p/Nim/lib/pure/pathnorm.nim");
						{
							NI TM__DfU0iuayCGwHDN1Exp9cbKg_13;
							NI TM__DfU0iuayCGwHDN1Exp9cbKg_14;
							if (!(((NI) 0) < d)) goto LA33_;
							nimln_(79, "/p/Nim/lib/pure/pathnorm.nim");
							TM__DfU0iuayCGwHDN1Exp9cbKg_13 = subInt(d, ((NI) 1));
							setLengthStrV2((&(*result)), ((NI)chckRange((NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_13), ((NI) 0), ((NI) 2147483647))));
							nimln_(80, "/p/Nim/lib/pure/pathnorm.nim");
							TM__DfU0iuayCGwHDN1Exp9cbKg_14 = subInt((*state), ((NI) 2));
							(*state) = (NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_14);
						}
						LA33_: ;
					}
					goto LA23_;
					LA25_: ;
					{
						NimStringV2 T43_;
						nimln_(82, "/p/Nim/lib/pure/pathnorm.nim");
						{
							NIM_BOOL T38_;
							NIM_CHAR T40_;
							T38_ = (NIM_BOOL)0;
							T38_ = (((NI) 0) < (*result).len);
							if (!(T38_)) goto LA39_;
							T40_ = (NIM_CHAR)0;
							T40_ = X5BX5D___okzHJ6GE9cv0bYG3b4r5KCAsystem((*result), ((NI) 1));
							T38_ = !((((NU8)(T40_)) == ((NU8)(47)) || ((NU8)(T40_)) == ((NU8)(47))));
							LA39_: ;
							if (!T38_) goto LA41_;
							nimln_(83, "/p/Nim/lib/pure/pathnorm.nim");
							nimAddCharV1((&(*result)), dirSep);
						}
						LA41_: ;
						nimln_(84, "/p/Nim/lib/pure/pathnorm.nim");
						nimln_(34, "/p/Nim/lib/system/fatal.nim");
						nimln_(84, "/p/Nim/lib/pure/pathnorm.nim");
						T43_.len = 0; T43_.p = NIM_NIL;
						T43_ = substr__2yh9cer0ymNRHlOOg8P7IuA(x, b.Field0, b.Field1);
						nimln_(34, "/p/Nim/lib/system/fatal.nim");
						eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T43_);
						prepareAdd((&(*result)), colontmpD_.len + 0);
appendString((&(*result)), colontmpD_);
					}
					LA23_: ;
				}
				goto LA13_;
				LA21_: ;
				{
					NIM_BOOL T45_;
					nimln_(85, "/p/Nim/lib/pure/pathnorm.nim");
					T45_ = (NIM_BOOL)0;
					T45_ = isDot__Sl9c33djPmHfV9bnZbQf0QBw_3(x, b);
					if (!T45_) goto LA46_;
				}
				goto LA13_;
				LA46_: ;
				{
					NimStringV2 T58_;
					NI TM__DfU0iuayCGwHDN1Exp9cbKg_18;
					nimln_(87, "/p/Nim/lib/pure/pathnorm.nim");
					if (!(b.Field0 <= b.Field1)) goto LA49_;
					nimln_(88, "/p/Nim/lib/pure/pathnorm.nim");
					{
						NIM_BOOL T53_;
						NIM_CHAR T55_;
						T53_ = (NIM_BOOL)0;
						T53_ = (((NI) 0) < (*result).len);
						if (!(T53_)) goto LA54_;
						T55_ = (NIM_CHAR)0;
						T55_ = X5BX5D___okzHJ6GE9cv0bYG3b4r5KCAsystem((*result), ((NI) 1));
						T53_ = !((((NU8)(T55_)) == ((NU8)(47)) || ((NU8)(T55_)) == ((NU8)(47))));
						LA54_: ;
						if (!T53_) goto LA56_;
						nimln_(89, "/p/Nim/lib/pure/pathnorm.nim");
						nimAddCharV1((&(*result)), dirSep);
					}
					LA56_: ;
					nimln_(90, "/p/Nim/lib/pure/pathnorm.nim");
					nimln_(34, "/p/Nim/lib/system/fatal.nim");
					nimln_(90, "/p/Nim/lib/pure/pathnorm.nim");
					T58_.len = 0; T58_.p = NIM_NIL;
					T58_ = substr__2yh9cer0ymNRHlOOg8P7IuA(x, b.Field0, b.Field1);
					nimln_(34, "/p/Nim/lib/system/fatal.nim");
					eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__2), T58_);
					prepareAdd((&(*result)), colontmpD__2.len + 0);
appendString((&(*result)), colontmpD__2);
					nimln_(91, "/p/Nim/lib/pure/pathnorm.nim");
					TM__DfU0iuayCGwHDN1Exp9cbKg_18 = addInt((*state), ((NI) 2));
					(*state) = (NI)(TM__DfU0iuayCGwHDN1Exp9cbKg_18);
				}
				goto LA13_;
				LA49_: ;
				LA13_: ;
			} LA11: ;
		}
		nimln_(92, "/p/Nim/lib/pure/pathnorm.nim");
		{
			NIM_BOOL T61_;
			T61_ = (NIM_BOOL)0;
			T61_ = ((*result).len == 0);
			if (!(T61_)) goto LA62_;
			T61_ = !((x.len == 0));
			LA62_: ;
			if (!T61_) goto LA63_;
			nimln_(34, "/p/Nim/lib/system/fatal.nim");
			eq___aBBXmHFBEivKqERloP6zmA_2((&(*result)), TM__DfU0iuayCGwHDN1Exp9cbKg_20);
		}
		LA63_: ;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame(_nimCurFrame);
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}
	if (TM__DfU0iuayCGwHDN1Exp9cbKg_2.status != 0) reraiseException();
	popFrame();
}
