/* Generated by Nim Compiler v0.20.99 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct AllocatorObj AllocatorObj;
typedef struct TNimType TNimType;
struct TNimType {
void* destructor;
NI size;
NCSTRING name;
};
typedef N_NIMCALL_PTR(void*, tyProc__g4DU8Xso7TeLfKjjMA54hg) (AllocatorObj* a, NI size, NI alignment);
typedef N_NIMCALL_PTR(void, tyProc__f0fmYWZ9bBl5n2coKW0dYBQ) (AllocatorObj* a, void* p, NI size);
typedef N_NIMCALL_PTR(void*, tyProc__pc9bof8Viqlm9byLAeLaBy4g) (AllocatorObj* a, void* p, NI oldSize, NI newSize);
typedef N_NIMCALL_PTR(void, tyProc__up7108S0Kt9cUg781lCWRSQ) (AllocatorObj* a);
typedef NU8 tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg;
struct AllocatorObj {
TNimType* m_type;
tyProc__g4DU8Xso7TeLfKjjMA54hg alloc;
tyProc__f0fmYWZ9bBl5n2coKW0dYBQ dealloc;
tyProc__pc9bof8Viqlm9byLAeLaBy4g realloc;
tyProc__up7108S0Kt9cUg781lCWRSQ deallocAll;
tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg flags;
NCSTRING name;
NI allocCount;
NI deallocCount;
};
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___tFR3xnzLW6sa9aQlh3AYf9cg)(AllocatorObj* dest);
N_LIB_PRIVATE N_NIMCALL(void*, colonanonymous___iJMelSyRU6RWIBySdiz9a5A)(AllocatorObj* a, NI size, NI alignment);
N_LIB_PRIVATE N_NOCONV(void*, alloc0__WrVG9abV9chlTLqkiXYLKwUg)(NI size);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___La9bTlQ9c9b9cB1WAOyENIt6Ig)(AllocatorObj* a, void* p, NI size);
N_LIB_PRIVATE N_NOCONV(void, dealloc__lmwgHsdhTsrQaepFju8wew)(void* p);
N_LIB_PRIVATE N_NIMCALL(void*, colonanonymous___3oPBf9aBNzv9c0DCHOew9a65Q)(AllocatorObj* a, void* p, NI oldSize, NI newSize);
N_LIB_PRIVATE N_NOCONV(void*, realloc__EIuTxhlMorNfTFWwy4AzTA)(void* p, NI newSize);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
static N_INLINE(NI, subInt)(NI a, NI b);
AllocatorObj* localAllocator__Fo4FsHewuC4VzDNrMpf3Og;
AllocatorObj* sharedAllocator__14UnoPGASR4x3NgNJ5Y5lA;
AllocatorObj allocatorStorage__9abMNjDlLVxVrfWZARGJwzw;
TNimType NTI__d9aje06sbOkiVogdUrGOkfQ_;

N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___tFR3xnzLW6sa9aQlh3AYf9cg)(AllocatorObj* dest) {
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void*, colonanonymous___iJMelSyRU6RWIBySdiz9a5A)(AllocatorObj* a, NI size, NI alignment) {
	void* result;
	NI TM__swLlbja8p0i4f2bNaYLjXA_2;
	result = (void*)0;
	result = alloc0__WrVG9abV9chlTLqkiXYLKwUg(((NI)chckRange(size, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	TM__swLlbja8p0i4f2bNaYLjXA_2 = addInt((*a).allocCount, ((NI) 1));
	(*a).allocCount = (NI)(TM__swLlbja8p0i4f2bNaYLjXA_2);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___La9bTlQ9c9b9cB1WAOyENIt6Ig)(AllocatorObj* a, void* p, NI size) {
	NI TM__swLlbja8p0i4f2bNaYLjXA_3;
	dealloc__lmwgHsdhTsrQaepFju8wew(p);
	TM__swLlbja8p0i4f2bNaYLjXA_3 = addInt((*a).deallocCount, ((NI) 1));
	(*a).deallocCount = (NI)(TM__swLlbja8p0i4f2bNaYLjXA_3);
}

static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}

static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void*, colonanonymous___3oPBf9aBNzv9c0DCHOew9a65Q)(AllocatorObj* a, void* p, NI oldSize, NI newSize) {
	void* result;
	NI TM__swLlbja8p0i4f2bNaYLjXA_4;
	result = (void*)0;
	result = realloc__EIuTxhlMorNfTFWwy4AzTA(p, ((NI)chckRange(newSize, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	TM__swLlbja8p0i4f2bNaYLjXA_4 = subInt(newSize, oldSize);
	nimZeroMem(((void*) ((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(oldSize)))), ((NI)chckRange((NI)(TM__swLlbja8p0i4f2bNaYLjXA_4), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(AllocatorObj*, getLocalAllocator__9c1gnSB0ooi2TBl9a6M3edDw)(void) {
	AllocatorObj* result;
	result = (AllocatorObj*)0;
	result = localAllocator__Fo4FsHewuC4VzDNrMpf3Og;
	{
		if (!(result == NIM_NIL)) goto LA3_;
		result = (&allocatorStorage__9abMNjDlLVxVrfWZARGJwzw);
		(*result).alloc = colonanonymous___iJMelSyRU6RWIBySdiz9a5A;
		(*result).dealloc = colonanonymous___La9bTlQ9c9b9cB1WAOyENIt6Ig;
		(*result).realloc = colonanonymous___3oPBf9aBNzv9c0DCHOew9a65Q;
		(*result).deallocAll = NIM_NIL;
		(*result).flags = 3;
		(*result).name = "nim_local";
		localAllocator__Fo4FsHewuC4VzDNrMpf3Og = result;
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_allocatorsInit000)(void) {
{
	TFrame FR_; FR_.len = 0;
	allocatorStorage__9abMNjDlLVxVrfWZARGJwzw.m_type = (&NTI__d9aje06sbOkiVogdUrGOkfQ_);
}
{
}
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_allocatorsDatInit000)(void) {
NTI__d9aje06sbOkiVogdUrGOkfQ_.destructor = (void*)eqdestroy___tFR3xnzLW6sa9aQlh3AYf9cg; NTI__d9aje06sbOkiVogdUrGOkfQ_.size = sizeof(AllocatorObj); NTI__d9aje06sbOkiVogdUrGOkfQ_.name = "|stdlib.allocators.AllocatorObj|";
}

